# Python Mastery Handbook — Complete (Single Page)


The five chapters appear below in order: Comprehensions, then Iterators & Generators, Functional Programming, Decorators & Properties, and finally Object-Oriented Programming. Use the table of contents just below to jump straight to any chapter or section.

## Table of Contents

1. **[Chapter 1: Python Comprehensions](#ch1)**
    - [Learning Objectives](#ch1-learning-objectives)
    - [Concept Explanation](#ch1-concept-explanation)
    - [List Comprehensions](#ch1-list-comprehensions)
    - [Dictionary Comprehensions](#ch1-dictionary-comprehensions)
    - [Set Comprehensions](#ch1-set-comprehensions)
    - [Generator Expressions (a teaser)](#ch1-generator-expressions-a-teaser)
    - [Comprehension vs Loop — When to Use Which](#ch1-comprehension-vs-loop-when-to-use-which)
    - [Performance & Best Practices](#ch1-performance-best-practices)
    - [Real Industry Usage](#ch1-real-industry-usage)
    - [Quick Recap](#ch1-quick-recap)
    - [Interview Questions](#ch1-interview-questions)
    - [Practice Exercises](#ch1-practice-exercises)
    - [Challenge Project](#ch1-challenge-project)

2. **[Chapter 2: Iterators & Generators](#ch2)**
    - [Learning Objectives](#ch2-learning-objectives)
    - [Concept Explanation](#ch2-concept-explanation)
    - [Iterators](#ch2-iterators)
    - [Generators](#ch2-generators)
    - [Building a Custom Iterator (the protocol)](#ch2-building-a-custom-iterator-the-protocol)
    - [Lazy Evaluation & Memory](#ch2-lazy-evaluation-memory)
    - [Real Industry Usage](#ch2-real-industry-usage)
    - [Quick Recap](#ch2-quick-recap)
    - [Interview Questions](#ch2-interview-questions)
    - [Practice Exercises](#ch2-practice-exercises)
    - [Challenge Project](#ch2-challenge-project)

3. **[Chapter 3: Functional Programming](#ch3)**
    - [Learning Objectives](#ch3-learning-objectives)
    - [Concept Explanation](#ch3-concept-explanation)
    - [Higher-Order Functions](#ch3-higher-order-functions)
    - [Lambda Functions](#ch3-lambda-functions)
    - [Built-in Higher-Order Functions](#ch3-built-in-higher-order-functions)
    - [Real Industry Usage](#ch3-real-industry-usage)
    - [Quick Recap](#ch3-quick-recap)
    - [Interview Questions](#ch3-interview-questions)
    - [Practice Exercises](#ch3-practice-exercises)
    - [Challenge Project](#ch3-challenge-project)

4. **[Chapter 4: Decorators & Properties](#ch4)**
    - [Learning Objectives](#ch4-learning-objectives)
    - [Concept Explanation](#ch4-concept-explanation)
    - [Writing Your First Decorator](#ch4-writing-your-first-decorator)
    - [Real-World Decorator: Validation / Auth](#ch4-real-world-decorator-validation-auth)
    - [The @property Decorator](#ch4-the-property-decorator)
    - [Real Industry Usage](#ch4-real-industry-usage)
    - [Quick Recap](#ch4-quick-recap)
    - [Interview Questions](#ch4-interview-questions)
    - [Practice Exercises](#ch4-practice-exercises)
    - [Challenge Project](#ch4-challenge-project)

5. **[Chapter 5: Object-Oriented Programming (OOP)](#ch5)**
    - [Learning Objectives](#ch5-learning-objectives)
    - [Why OOP? Concept Explanation](#ch5-why-oop-concept-explanation)
    - [Classes & Objects](#ch5-classes-objects)
    - [Attributes & Methods](#ch5-attributes-methods)
    - [The Four Pillars of OOP](#ch5-the-four-pillars-of-oop)
    - [Real Industry Usage](#ch5-real-industry-usage)
    - [Quick Recap](#ch5-quick-recap)
    - [Interview Questions](#ch5-interview-questions)
    - [Practice Exercises](#ch5-practice-exercises)
    - [Challenge Project — Mini Library Management System](#ch5-challenge-project-mini-library-management-system)

<a id="ch1"></a>

# Chapter 1: Python Comprehensions

> A comprehension is Python's way of saying "build this collection from that one" in a single, readable line. It's one of the first features that makes Python feel like Python, and you'll run into it everywhere in real code, from data cleaning to API plumbing.

<a id="ch1-learning-objectives"></a>

## Learning Objectives

By the end of this chapter you should be able to:

- Take an ordinary `for`-loop that builds a collection and rewrite it as a comprehension.
- Recognize the four kinds of comprehension: list, dictionary, set, and generator expressions.
- Filter (`if`) and transform (the expression) data in a single line.
- Decide when a comprehension is the right tool, and when a plain loop is genuinely clearer.
- Explain why generator expressions are lazy and how they differ from list comprehensions in how they use memory.
- See how comprehensions show up in real work: ETL, feature engineering, deduplication, and config building.

---

<a id="ch1-concept-explanation"></a>

## Concept Explanation

A comprehension is a compact syntax for building a new collection (list, dict, or set) by looping over an existing iterable, optionally filtering items, and transforming each one.

The general shape of a list comprehension is:

```text
[ expression   for item in iterable   if condition ]
   └────┬────┘   └───────┬────────┘   └────┬─────┘
   transform        loop source         filter
```

- `expression` — what to do with each item (e.g. `i`, `i**2`, `i.upper()`). This is the value that ends up in the new collection.
- `for item in iterable` — the loop. `item` is the loop variable; `iterable` is the source (a `range`, list, string, dict, etc.).
- `if condition` — optional. Keep an item only when the condition is `True`.

### Beginner explanation

Say you have a basket of numbers and you want a new basket with each number doubled. The old way is to make an empty basket, loop over the numbers, and `append` each doubled number. A comprehension lets you describe the same idea in one line: "give me `i*2` for each `i` in the basket."

### Intermediate explanation

A comprehension is an expression, not a statement. It evaluates to a value (a brand-new list/dict/set) that you can assign, pass to a function, or return directly. Python still runs a loop under the hood, but the looping machinery is baked into the syntax. The optional `if` acts as a gatekeeper: items that fail the condition never make it into the output.

### Advanced explanation

Each comprehension type maps to a literal constructor:

| Type | Brackets | Produces |
|------|----------|----------|
| List | `[ ... ]` | a `list` (ordered, indexable, allows duplicates) |
| Dict | `{ k: v ... }` | a `dict` (key → value mapping, keys unique) |
| Set | `{ ... }` | a `set` (unordered, **no duplicates**) |
| Generator | `( ... )` | a lazy `generator` (yields items one at a time) |

The expression part is evaluated in its own scope. In Python 3 the loop variable does not leak into the surrounding namespace. Generator expressions are the odd one out: they don't materialize anything up front, they produce values on demand, which is what makes them memory-efficient for large or infinite streams.

### Real-world intuition

Picture a comprehension as a conveyor belt in a factory:

1. Raw items roll in from the iterable.
2. A filter gate (`if`) lets some through and rejects others.
3. A transform station (`expression`) reshapes each item.
4. Finished items drop into the collection bin (list, dict, or set).

### A visual analogy

A comprehension reads almost like an English sentence: "Give me the square of each number in 1 to 5 where the number is even." The Python is nearly a word-for-word translation: `[n**2 for n in range(1,6) if n % 2 == 0]`.

```mermaid
flowchart LR
    A[Iterable<br/>range / list / string] --> B{Filter<br/>if condition}
    B -- keep --> C[Transform<br/>expression]
    B -- drop --> X[(discarded)]
    C --> D[Collect into<br/>list / dict / set]
```

---

<a id="ch1-list-comprehensions"></a>

## List Comprehensions

A list comprehension builds a new `list`. We'll start from the loop version so you can watch the transformation happen, then tighten it into a comprehension.

### From a loop to a comprehension

#### Original Code

In [1]:
# The "old way": build a list by appending in a loop
num = []
for i in range(1, 6):
    num.append(i)
print(num)

[1, 2, 3, 4, 5]


In [2]:
# The comprehension way: same result, one line
num = [i for i in range(1, 6)]
print(num)

[1, 2, 3, 4, 5]


#### What This Code Does

- **Purpose:** Build a list of the numbers 1 through 5.
- **Inputs:** `range(1, 6)` — an iterable yielding `1, 2, 3, 4, 5` (the stop value `6` is excluded).
- **Outputs:** A list `[1, 2, 3, 4, 5]`.
- **Logic:** Iterate over the range; collect each value into a list.
- **Key concepts:** `range()`, `list.append()`, list comprehension syntax, half-open ranges.

#### Line-by-Line Breakdown

- `num = []` — start with an empty list (the bin).
- `for i in range(1, 6):` — loop over `1..5`.
- `num.append(i)` — add each value.
- `num = [i for i in range(1, 6)]` — the comprehension does all three steps at once: the bin (`[]`), the loop (`for i in...`), and the collection (`i`).

#### Why This Output Occurs

`range(1, 6)` produces `1, 2, 3, 4, 5` — the upper bound is exclusive. Both versions collect every value unchanged, so both print the same list.

#### Common Mistakes

- Expecting `range(1, 6)` to include `6`. It stops before the second argument.
- Forgetting that `num.append(...)` returns `None` — never write `num = num.append(i)`.
- When you're just collecting items as-is, prefer `list(range(1, 6))`. Reach for a comprehension when you also need to transform or filter.

---

### Transforming items: squares

#### Original Code

In [ ]:
num = [i**2 for i in range(1, 6)]
print(num)

[1, 4, 9, 16, 25]


#### What This Code Does

- **Purpose:** Build a list of squares of 1 through 5.
- **Inputs:** `range(1, 6)`.
- **Outputs:** `[1, 4, 9, 16, 25]`.
- **Logic:** For each `i`, compute `i**2` and collect it.
- **Key concepts:** The expression part can be any expression, not just the bare variable.

#### Line-by-Line Breakdown

- `i**2` — the transform: raise each item to the power of 2 (`**` is exponentiation).
- `for i in range(1, 6)` — supplies `1..5`.

#### Why This Output Occurs

Each `i` is squared: `1²=1`, `2²=4`, `3²=9`, `4²=16`, `5²=25`.

#### Common Mistakes

- Confusing `i**2` (power) with `i^2`. The `^` operator is bitwise XOR, not exponentiation, so `3^2` is `1`, not `9`.
- The expression runs once per item, so keep it cheap inside large comprehensions.

---

### Filtering: even numbers only

#### Original Code

In [ ]:
num = [1, 2, 3, 4, 5, 6, 7, 8, 9]
even = [i for i in num if i % 2 == 0]
print(even)

[2, 4, 6, 8]


#### What This Code Does

- **Purpose:** Keep only the even numbers from a list.
- **Inputs:** `num`, a list of integers 1–9.
- **Outputs:** `[2, 4, 6, 8]`.
- **Logic:** For each `i`, keep it only when `i % 2 == 0`.
- **Key concepts:** The `if` filter, the modulo operator `%`.

#### Line-by-Line Breakdown

- `if i % 2 == 0` — `i % 2` is the remainder when dividing by 2; it's `0` for even numbers.
- Items that fail this test are never added to `even`.

#### Why This Output Occurs

Only `2, 4, 6, 8` satisfy `i % 2 == 0`. The odd numbers are filtered out.

#### Common Mistakes

- Writing `if i % 2 = 0`. A single `=` is assignment and raises a syntax error. Use `==` for comparison.
- Placing the `if` before the `for` when there's no `else`. The filter form is `[expr for x in it if cond]`. The `if/else` ternary form goes before the `for`, which is covered below.

!!! note "Filter `if` vs. ternary `if/else`"
    These two are different:

    - **Filter** (after `for`): `[i for i in num if i % 2 == 0]` → drops odd numbers.
    - **Ternary** (before `for`): `["even" if i % 2 == 0 else "odd" for i in num]` → keeps every item but transforms it.

---

### Transforming strings: uppercase words

#### Original Code

In [3]:
words = ["python", "java", "c++", "ruby"]
upper = [i.upper() for i in words]
print(upper)

['PYTHON', 'JAVA', 'C++', 'RUBY']


#### What This Code Does

- **Purpose:** Uppercase every word in a list.
- **Inputs:** `words`, a list of lowercase strings.
- **Outputs:** `['PYTHON', 'JAVA', 'C++', 'RUBY']`.
- **Logic:** Call `.upper()` on each string.
- **Key concepts:** Comprehensions work on any iterable, including lists of strings; string methods.

#### Line-by-Line Breakdown

- `i.upper()` — the transform: returns an uppercase copy of the string. Strings are immutable, so the original list is untouched.

#### Why This Output Occurs

`.upper()` converts alphabetic characters to uppercase. `c++` becomes `C++` because the `+` symbols have no upper or lower case, so they're left alone.

#### Common Mistakes

- Expecting `.upper()` to modify the original strings. It returns a new string; the originals in `words` stay lowercase.
- Naming the loop variable `i` for strings is a little misleading. `word` reads better: `[word.upper() for word in words]`.

---

### Range filter with a chained comparison

#### Original Code

In [ ]:
num = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
filtered = [i for i in num if 3 <= i <= 8]
print(filtered)

[3, 4, 5, 6, 7, 8]


#### What This Code Does

- **Purpose:** Keep numbers within the inclusive range 3 to 8.
- **Inputs:** `num`, integers 1–10.
- **Outputs:** `[3, 4, 5, 6, 7, 8]`.
- **Logic:** Use a chained comparison `3 <= i <= 8` as the filter.
- **Key concepts:** Python's chained comparisons (a feature many languages lack).

#### Line-by-Line Breakdown

- `if 3 <= i <= 8` — reads naturally as "i is between 3 and 8 inclusive." Python evaluates it as `(3 <= i) and (i <= 8)`.

#### Why This Output Occurs

`1, 2` are below 3 and `9, 10` are above 8, so they're dropped. Everything from 3 to 8 passes.

#### Common Mistakes

- Chained comparisons are a real Python feature. In many languages you'd have to write `i >= 3 && i <= 8`. In Python, `3 <= i <= 8` is idiomatic and clearer.
- Don't chain unrelated comparisons like `a < b > c`. It's legal syntax but confusing.

---

<a id="ch1-dictionary-comprehensions"></a>

## Dictionary Comprehensions

A dictionary comprehension builds a `dict` using a `key: value` expression: `{key_expr: value_expr for item in iterable}`.

### Mapping numbers to their squares

#### Original Code

In [ ]:
d = {i: i**2 for i in range(1, 6)}
print(d)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}


#### What This Code Does

- **Purpose:** Build a mapping of each number to its square.
- **Inputs:** `range(1, 6)`.
- **Outputs:** `{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}`.
- **Logic:** For each `i`, use `i` as the key and `i**2` as the value.
- **Key concepts:** The `key: value` syntax is what distinguishes a dict comprehension from a set comprehension.

#### Line-by-Line Breakdown

- `{i: i**2 ...}` — the colon separates key (`i`) from value (`i**2`).
- `for i in range(1, 6)` — supplies the keys `1..5`.

#### Why This Output Occurs

Each key is the number; each value is its square.

#### Common Mistakes

- `{i for i in range(5)}` (no colon) is a set, not a dict. The colon is what makes it a dict.
- Duplicate keys silently overwrite: `{k: v for ...}` keeps the last value for any repeated key.

---

### Building a dict by index

#### Original Code

In [ ]:
num = [1, 2, 3, 4, 5]
d = {i: num[i] for i in range(len(num))}
print(d)

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5}


#### What This Code Does

- **Purpose:** Map each list index to the value stored at that index.
- **Inputs:** `num`, a list of 5 integers.
- **Outputs:** `{0: 1, 1: 2, 2: 3, 3: 4, 4: 5}`.
- **Logic:** Loop over indices `0..4`; key is the index `i`, value is `num[i]`.
- **Key concepts:** `len()`, indexing, `range(len(...))`.

#### Line-by-Line Breakdown

- `range(len(num))` — produces `0, 1, 2, 3, 4` (valid indices).
- `i: num[i]` — index as key, element as value.

#### Why This Output Occurs

Index `0` holds `1`, index `1` holds `2`, and so on.

#### Common Mistakes

- The Pythonic way to get index/value pairs is `enumerate`: `{i: v for i, v in enumerate(num)}`. It avoids `range(len(...))` and is far easier to read.
- `range(len(num))` off-by-one errors are common when you mistakenly write `range(1, len(num))` and lose the first element.

---

### Swapping keys and values

#### Original Code

In [ ]:
d = {1: 1, 2: 4, 3: 9, 4: 16, 5: 25}
{value: key for key, value in d.items()}

{1: 1, 4: 2, 9: 3, 16: 4, 25: 5}


#### What This Code Does

- **Purpose:** Invert a dictionary — turn values into keys and keys into values.
- **Inputs:** `d`, mapping numbers to squares.
- **Outputs:** `{1: 1, 4: 2, 9: 3, 16: 4, 25: 5}`.
- **Logic:** Iterate over `d.items()` (key/value pairs) and emit `value: key`.
- **Key concepts:** `dict.items()`, tuple unpacking (`key, value`).

#### Line-by-Line Breakdown

- `d.items()` — yields pairs like `(1, 1)`, `(2, 4)`, ...
- `for key, value in d.items()` — unpacks each pair into `key` and `value`.
- `value: key` — flips them so the old value becomes the new key.

#### Why This Output Occurs

`(2, 4)` becomes `4: 2`, `(3, 9)` becomes `9: 3`, and so on. The original value is now the key.

#### Common Mistakes

- Inverting only works cleanly when the values are unique and hashable. If two keys share a value, the inverted dict keeps only the last one.
- This cell's result wasn't `print`ed. In a Jupyter notebook the last expression is auto-displayed, but in a `.py` script you'd need `print(...)` to see it.

---

### Filtering a dict by value (a teaching bug)

#### Original Code

In [18]:
# The original comment claimed: "filter key greater than 3"
d = {1:1,2:4,3:9,4:16,5:25}


# ...but the code actually filters on VALUE >= 3
nums_greater_then_3 = {key: value for key, value in d.items() if value >= 3}
print(nums_greater_then_3)

{2: 4, 3: 9, 4: 16, 5: 25}


#### What This Code Does

- **Purpose (as written):** Keep entries whose value is at least 3.
- **Inputs:** `d = {1: 1, 2: 4, 3: 9, 4: 16, 5: 25}`.
- **Outputs:** `{2: 4, 3: 9, 4: 16, 5: 25}`.
- **Logic:** Keep a pair only if `value >= 3`.
- **Key concepts:** Filtering in a dict comprehension; intent vs. implementation.

#### Line-by-Line Breakdown

- `if value >= 3` — the filter looks at the value, not the key.
- The pair `1: 1` is dropped because its value `1` is less than `3`. Every other value (`4, 9, 16, 25`) passes.

#### Why This Output Occurs

Only `1: 1` fails the `value >= 3` test. Notice the keys in the result are `2, 3, 4, 5`, which is not what "filter key greater than 3" would produce.

#### Common Mistakes

!!! warning "Intent vs. actual condition — the classic comprehension bug"
    The original comment said "filter key greater than 3" but the code filters on value. These produce different results:

    - **What the comment described** (`if key > 3`): `{4: 16, 5: 25}`.
    - **What the code actually does** (`if value >= 3`): `{2: 4, 3: 9, 4: 16, 5: 25}`.

    When a comment and the code disagree, trust the code and fix the comment, then double-check what the author actually intended. Filtering on the wrong field (key vs. value) is one of the most common silent bugs in dict comprehensions.

---

<a id="ch1-set-comprehensions"></a>

## Set Comprehensions

A set comprehension uses `{ ... }` (like a dict but with no colon) and produces a `set`: an unordered collection with no duplicates.

!!! note "Set ordering is not guaranteed"
    A `set` has no defined order. When you `print` one, the arrangement you see is an implementation detail of the hash table — it can differ between runs or Python versions. To get a predictable order, wrap it in `sorted(...)`.

### Fifth powers (sorted for a stable display)

#### Original Code

In [ ]:
s = {i**5 for i in range(1, 6)}
print(sorted(s))

[1, 32, 243, 1024, 3125]


#### What This Code Does

- **Purpose:** Compute the set of fifth powers of 1–5, then display them in order.
- **Inputs:** `range(1, 6)`.
- **Outputs:** `[1, 32, 243, 1024, 3125]`.
- **Logic:** Build a set of `i**5`, then `sorted()` for a deterministic list.
- **Key concepts:** Set comprehension, `sorted()` returning a list.

#### Line-by-Line Breakdown

- `{i**5 for i in range(1, 6)}` — a set comprehension (no colon, so it's a set, not a dict).
- `sorted(s)` — returns a sorted list of the set's elements, which is why the output is shown with `[ ]`, not `{ }`.

#### Why This Output Occurs

`1⁵=1`, `2⁵=32`, `3⁵=243`, `4⁵=1024`, `5⁵=3125`. All distinct, so nothing is deduplicated, and `sorted()` arranges them ascending.

#### Common Mistakes

- Expecting `print(s)` (without `sorted`) to show this neat order. It might not. Use `sorted()` whenever order matters for display or testing.
- `sorted()` returns a new list; the set `s` itself stays unordered.

---

### Unique characters in text

#### Original Code

In [ ]:
text = "hello how are you"
unique_chars = {i for i in text}
print(unique_chars)

{'o', 'a', 'h', 'e', 'w', 'l', 'r', ' ', 'u', 'y'}


#### What This Code Does

- **Purpose:** Find the distinct characters in a string (including the space).
- **Inputs:** the string `text`.
- **Outputs:** a set of unique characters.
- **Logic:** Iterate over each character; the set automatically discards duplicates.
- **Key concepts:** Strings are iterable (character by character); sets deduplicate.

#### Line-by-Line Breakdown

- `for i in text` — loops over each character of the string.
- `{i for i in text}` — collects them into a set, so repeated letters appear only once.

#### Why This Output Occurs

The letters `l` and `o` appear several times in the text but show up only once. The space `' '` is a character too, so it's included. The order shown is arbitrary, so yours may differ.

#### Common Mistakes

- Forgetting that whitespace counts as a character. To exclude it, filter: `{c for c in text if not c.isspace()}`.
- `set(text)` does the exact same thing more concisely. Use the comprehension only when you also transform or filter.

---

### Filtering evens into a set

#### Original Code

In [ ]:
num = [1, 2, 3, 4, 4, 6, 5, 6, 7, 8, 9]
even = {i for i in num if i % 2 == 0}
print(even)

{8, 2, 4, 6}


#### What This Code Does

- **Purpose:** Collect the unique even numbers from a list that contains duplicates.
- **Inputs:** `num`, with repeated `4` and `6`.
- **Outputs:** `{8, 2, 4, 6}` (order not guaranteed).
- **Logic:** Filter for evens, and the set drops duplicates automatically.
- **Key concepts:** Combining filtering and deduplication in one step.

#### Line-by-Line Breakdown

- `if i % 2 == 0` — keep evens only.
- `{ ... }` — store in a set, so the duplicate `4` and `6` collapse to single entries.

#### Why This Output Occurs

The evens in the list are `2, 4, 4, 6, 6, 8`. The set collapses duplicates to `{2, 4, 6, 8}`, shown here in an arbitrary order.

#### Common Mistakes

- If you used a list comprehension instead (`[i for i in num if i % 2 == 0]`), you'd get `[2, 4, 4, 6, 6, 8]` with duplicates preserved. Choose set vs. list based on whether duplicates matter.
- Sets are the idiomatic, fast way to deduplicate while filtering.

---

<a id="ch1-generator-expressions-a-teaser"></a>

## Generator Expressions (a teaser)

A generator expression looks just like a list comprehension but uses parentheses `( ... )`. The key difference is that it doesn't build a collection in memory. It returns a lazy generator object that produces values one at a time, only when you ask for them.

#### Original Code

In [23]:
square = (i**2 for i in range(1, 10))
print(list(square))

[1, 4, 9, 16, 25, 36, 49, 64, 81]


#### What This Code Does

- **Purpose:** Create a lazy stream of squares without materializing a list.
- **Inputs:** `range(1, 10)`.
- **Outputs:** a generator object (not the values themselves).
- **Logic:** Nothing is computed yet — values are produced on demand when iterated.
- **Key concepts:** Lazy evaluation, generators, memory efficiency.

#### Line-by-Line Breakdown

- `(i**2 for i in range(1, 10))` — parentheses make this a generator expression, not a list.
- `print(square)` — prints the generator object's repr, not its contents, because no iteration has happened yet.

#### Why This Output Occurs

A generator hasn't computed anything when it's created. Printing it shows its memory address, not the squares. To get the values you have to iterate — for example `list(square)` → `[1, 4, 9, 16, 25, 36, 49, 64, 81]`, or loop over it, or call `next(square)`.

#### Common Mistakes

- Expecting `print(square)` to show the numbers. It shows the object. Convert with `list(...)` or iterate.
- Generators are single-use. Once exhausted, they're empty. You can't iterate the same generator twice.
- Use a generator (not a list) when feeding a large or streamed sequence into something like `sum(...)`, a `for` loop, or `any(...)`. You save memory by never building the full list.

!!! note "We'll go deep on this in Chapter 3"
    Generators, `yield`, and lazy iteration get their own full treatment later. For now, just remember: `( )` is a lazy generator, `[ ]` is an eager list. See Chapter 3 for the complete story.

---

<a id="ch1-comprehension-vs-loop-when-to-use-which"></a>

## Comprehension vs Loop — When to Use Which

| Concern | Comprehension | Plain `for` loop |
|---|---|---|
| **Readability (simple transform/filter)** | Wins — one expressive line | More boilerplate (`[]`, `.append`) |
| **Performance** | Usually faster (optimized, no repeated `.append` lookup) | Slightly slower for the same work |
| **Side effects** (printing, writing files, calling APIs) | Avoid — comprehensions are for building collections | Use a loop |
| **Complex / multi-step logic** | Becomes cryptic fast | Loop with intermediate variables is clearer |
| **Debugging (breakpoints, prints)** | Hard to step through | Easy to insert prints/breakpoints |
| **Memory (huge data)** | List comp builds it all | Loop or generator streams it |
| **Multiple outputs / accumulators at once** | Awkward | Loop handles it naturally |

!!! tip "Rule of thumb"
    If you can read the comprehension out loud as a single clear sentence, use it. The moment you need nested `if/else`, multiple `for` clauses, and a complex expression all at once, a loop is kinder to whoever reads your code next.

---

<a id="ch1-performance-best-practices"></a>

## Performance & Best Practices

A list comprehension avoids the per-iteration attribute lookup and method call of `list.append`, so it's usually faster than the hand-written loop that does the same thing. For tight numeric work over large data, that difference adds up.

When you only consume the result once, reach for a generator. `sum(i**2 for i in range(1_000_000))` never builds a million-element list — it streams. Prefer `( )` over `[ ]` when the result is handed straight to `sum`, `any`, `all`, `max`, `min`, or a single loop.

!!! warning "Don't write overly clever one-liners"
    Nested comprehensions like `[x for row in matrix for x in row if x > 0]` are fine once you know the read order (left-to-right is outer-to-inner loop). But triple-nested comprehensions with multiple conditions turn into write-only code. If a teammate has to stop and decode it, refactor to a loop or a helper function.

!!! warning "No side effects inside comprehensions"
    `[print(x) for x in items]` "works," but it builds a throwaway list of `None`s purely for the side effect. That's a misuse. Use a plain `for` loop when the goal is doing something, not building something.

!!! note "Nested comprehension read order"
    `[expr for a in outer for b in inner]` is equivalent to two nested loops written in the same left-to-right order. The first `for` is the outer loop.

---

<a id="ch1-real-industry-usage"></a>

## Real Industry Usage

Comprehensions are everywhere in production Python. A few patterns you'll see again and again:

- **Data cleaning / ETL** — normalize records in one pass: `[row.strip().lower() for row in raw_lines if row.strip()]` drops blank lines and tidies the rest.
- **Feature engineering (pandas / ML)** — building derived columns or label maps, e.g. `label_to_id = {label: idx for idx, label in enumerate(sorted(classes))}`, which is a staple before training a classifier.
- **Lookup dicts & config maps** — turning a list of objects into an O(1) lookup: `users_by_id = {u.id: u for u in users}`.
- **Deduplication with sets** — `unique_emails = {u.email.lower() for u in users}` collapses duplicates and normalizes case in one line.
- **Log / event filtering** — `errors = [line for line in log if "ERROR" in line]` is the bread and butter of quick log triage, and as a generator it scales to multi-gigabyte logs without loading them into memory.

---

<a id="ch1-quick-recap"></a>

## Quick Recap

- A comprehension is `[ expression for item in iterable if condition ]` — transform, loop, optional filter.
- `[ ]` → list, `{k: v}` → dict, `{ }` (no colon) → set, `( )` → lazy generator.
- The filter `if` (after `for`) drops items; the ternary `if/else` (before `for`) transforms every item.
- Sets are unordered and deduplicate. Use `sorted()` for a stable display.
- Generators are lazy and single-use. They print as an object until you iterate them.
- Reach for a loop when you need side effects, complex logic, or easy debugging.
- Comprehensions are typically faster than equivalent append loops, and they're idiomatic for ETL, lookups, and deduplication.

---

<a id="ch1-interview-questions"></a>

## Interview Questions

### Beginner

??? note "Show answer — What is a list comprehension and what are its three parts?"
    A list comprehension is a concise way to build a list from an iterable. Its parts are the **expression** (what to put in the list), the **`for` clause** (the loop over an iterable), and an optional **`if` filter**. Example: `[i**2 for i in range(5) if i % 2 == 0]`.

??? note "Show answer — How do you write a comprehension that keeps only even numbers from a list `nums`?"
    `[n for n in nums if n % 2 == 0]`. The `if n % 2 == 0` filter keeps items whose remainder when divided by 2 is zero.

??? note "Show answer — What's the difference between `[ ]`, `{ }` with a colon, and `{ }` without a colon?"
    `[ ... ]` builds a **list**, `{ k: v ... }` builds a **dict** (the colon makes it a mapping), and `{ ... }` without a colon builds a **set** (unordered, no duplicates).

### Intermediate

??? note "Show answer — Why might `print(my_set)` show elements in a surprising order?"
    A `set` is unordered; its display order reflects the internal hash table, not insertion order, and isn't guaranteed across runs or versions. Use `sorted(my_set)` for a predictable order.

??? note "Show answer — When would you use a generator expression instead of a list comprehension?"
    When you only need to consume the values once and want to avoid building the whole collection in memory — e.g. `sum(x**2 for x in big_range)`. Generators are lazy (compute on demand) and memory-efficient, but single-use.

??? note "Show answer — How do you swap a dict's keys and values, and what can go wrong?"
    `{v: k for k, v in d.items()}`. It breaks if the original **values aren't unique** (later pairs overwrite earlier ones) or aren't **hashable** (lists/dicts can't be keys).

### Advanced

??? note "Show answer — Explain the read order of a nested comprehension `[x for row in matrix for x in row]`."
    It's equivalent to nested loops in the same order: `for row in matrix:` (outer) then `for x in row:` (inner), collecting each `x`. The leftmost `for` is the outermost loop. This flattens a 2D list into a 1D list.

??? note "Show answer — Does the loop variable in a comprehension leak into the enclosing scope?"
    No (in Python 3). Comprehensions have their own scope, so `[i for i in range(3)]` does **not** leave `i` defined afterwards. This differs from a plain `for` loop, where the variable *does* persist.

??? note "Show answer — A comment says 'filter keys > 3' but the code is `{k: v for k, v in d.items() if v >= 3}`. What's the bug and how do you reason about it?"
    The code filters on the **value** (`v`), not the **key** (`k`), so the comment is wrong. For `d = {1:1, 2:4, 3:9, 4:16, 5:25}`, the code yields `{2:4, 3:9, 4:16, 5:25}`, whereas `if k > 3` would yield `{4:16, 5:25}`. Always trust the code over the comment, then confirm the author's intent and fix whichever is wrong.

---

<a id="ch1-practice-exercises"></a>

## Practice Exercises

### **Easy**

1. Build a list of the cubes of 1 through 10 using a list comprehension.
2. From `["  hi  ", "bye", "  yo"]`, produce a list of the strings stripped of surrounding whitespace.
3. Create a set of the unique vowels present in the string `"education is powerful"`.

### **Medium**

1. Given `nums = [4, 7, 10, 13, 16, 19]`, use a dict comprehension to map each number to whether it's even (`{4: True, 7: False, ...}`).
2. From a list of words, build a dict mapping each word to its length, but only for words longer than 3 characters.
3. Use a generator expression to compute the sum of squares of all numbers from 1 to 100 — without ever building a list.

### **Hard**

1. Flatten a 2D list `matrix = [[1, 2], [3, 4], [5, 6]]` into a single list using a nested comprehension, keeping only even values.
2. Invert the dict `{"a": 1, "b": 2, "c": 2}` and explain (in a comment) what happens to the duplicate value `2`.
3. Given a list of log lines, build a dict that maps each log level (`"INFO"`, `"WARN"`, `"ERROR"`) to the **count** of lines containing it. (Hint: you may combine a comprehension with `str.count` or a helper.)

---

<a id="ch1-challenge-project"></a>

## Challenge Project

### Mini Log Analyzer

Build a small command-line tool that reads a server log and reports on it using comprehensions throughout.

**Spec**

Given a list of log lines like:

```text
2026-06-25 10:00 INFO user=alice action=login
2026-06-25 10:01 ERROR user=bob action=login msg=timeout
2026-06-25 10:02 WARN user=alice action=upload
2026-06-25 10:03 ERROR user=carol action=login msg=denied
```

Your tool should produce:

1. **Errors only** — a `list` of all lines containing `"ERROR"` (use a generator if the file is large).
2. **Unique users** — a `set` of every distinct `user=...` value mentioned.
3. **Level counts** — a `dict` mapping each level (`INFO`/`WARN`/`ERROR`) to how many lines have it.
4. **Login failures** — a `list` of `(user, msg)` pairs for `ERROR` lines whose `action=login`.

**Starter hints**

In [33]:
# Beginner
# question 1

list_of_cubes = [x*x*x for x in range(1,11)]

print(list_of_cubes)

[1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]


In [45]:
# Beginner
# question 2
list_of_wspace = [" hi","bye"," yo"]

list_of_no_whitespace = [x.strip() for x in list_of_wspace]

print(list_of_no_whitespace)

['hi', 'bye', 'yo']


In [47]:
# Beginner
# quetion 3
education = "Education is powerful".lower()

list_of_vowels = ["a","e","i","o","u"]
list_of_words = list(education)
print(f"list of words: {list_of_words}")
vowels_in_education = {x for x in education if x in list_of_vowels}

print(vowels_in_education)

list of words: ['e', 'd', 'u', 'c', 'a', 't', 'i', 'o', 'n', ' ', 'i', 's', ' ', 'p', 'o', 'w', 'e', 'r', 'f', 'u', 'l']
{'a', 'u', 'i', 'o', 'e'}


In [49]:
# Medium 
# 1
nums  = [4, 7, 10, 13, 16, 19]
even = {x:x % 2 == 0 for x in nums}

print(even)

{4: True, 7: False, 10: True, 13: False, 16: True, 19: False}


In [50]:
# Medium
# 2
list_of_sen = ["Nirbhay","and","Sumit","are","good","friends"]

words_length = {x:len(x) for x in list_of_sen if len(x) > 3}

print(words_length)

{'Nirbhay': 7, 'Sumit': 5, 'good': 4, 'friends': 7}


In [68]:
# Medium 
# 3
squares = (x for x in range(1,101) if x %2 == 0)
sum = 0
for x in squares:
    sum += x

print(sum)

2550


In [69]:
#for rows in matrix
#    for nums in rows
# Hard
# 1

matrix = [[1,2],[3,4],[5,6]]

single_list = [num for rows in matrix for num in rows if num % 2 == 0]
print(single_list)

[2, 4, 6]


In [73]:
# Hard
# 2
dict_hard_2 = {"a":1,"b":2,"c":2}

dict_hard_2_invert = {value:key for key,value in dict_hard_2.items()}

print(dict_hard_2_invert)

# because its dictionary and we cannot have dublicate key

{1: 'a', 2: 'c'}


In [ ]:
from collections import Counter
log_lines = [
    "2026-08-15 18:14:42,134 | DEBUG    | zara_pipeline | Loaded 3 config values",
    "2026-08-15 18:14:42,134 | INFO     | zara_pipeline | Connected to data source",
    "2026-08-15 18:14:42,135 | WARN     | zara_pipeline | 2 rows had missing values",
    "2026-08-15 18:14:42,135 | WARN     | zara_pipeline | 2 rows had missing values",
    "2026-08-15 18:14:42,135 | WARN     | zara_pipeline | 2 rows had missing values",
    "2026-08-15 18:14:42,136 | ERROR    | zara_pipeline | Failed to write output file"
]

log_level = ["INFO","WARN","ERROR"]

x = [a.split() for a in log_lines]

list_log = [string for row in x for string in row if string in log_level]

dict_counts = {v: list_log.count(v) for v in set(list_log)}

print(dict_counts)

['INFO', 'WARN', 'WARN', 'WARN', 'ERROR']
{'INFO': 1, 'ERROR': 1, 'WARN': 3}


In [156]:
lines = ["2026-06-25 10:00 INFO user=alice action=login",
        "2026-06-25 10:01 ERROR user=bob action=login msg=timeout",
        "2026-06-25 10:02 WARN user=alice action=upload",
        "2026-06-25 10:03 ERROR user=carol action=login msg=denied"]

only_error = (line for line in lines if "ERROR" in line.split())
error_list = list(only_error)
print(error_list)

def field(line,key):
    for token in line.split():
        if token.startswith(key+"="):
            return token[len(key) + 1:]
    return None

    
users = {field(ln,"user") for ln in lines if field(ln,"user")}

print(users)

status =["INFO","ERROR","WARN","ERROR"]

x = [a.split() for a in lines]

list_status = [stat for rows in x for stat in rows if stat in status]

status_list = { v:list_status.count(v) for v in set(list_status)}

print(status_list)

def login_failure(line,key,msg):

    if "action=login" not in line:
        return None
    
    user = None
    message = None

    for ln in line.split():
        if ln.startswith(key+"="):
            user = ln[len(key)+ 1:]
        elif ln.startswith(msg + "="):
            message = ln[len(msg)+ 1:]
        if user and message:
            return user, message
    return None

login_failure_user =[login_failure(ln,"user","msg") for ln in error_list if login_failure(ln,"user","msg")]

print(login_failure_user)





['2026-06-25 10:01 ERROR user=bob action=login msg=timeout', '2026-06-25 10:03 ERROR user=carol action=login msg=denied']
{'carol', 'alice', 'bob'}
{'INFO': 1, 'WARN': 1, 'ERROR': 2}
[('bob', 'timeout'), ('carol', 'denied')]


In [113]:
lines = ["2026-06-25 10:00 INFO user=alice action=login",
        "2026-06-25 10:01 ERROR user=bob action=login msg=timeout",
        "2026-06-25 10:02 WARN user=alice action=upload",
        "2026-06-25 10:03 ERROR user=carol action=login msg=denied"] # read from a file with open(path) as f: lines = f.read().splitlines()

# 1. Errors (lazy generator — only materialise when needed)
errors = (ln for ln in lines if "ERROR" in ln)

# 2. Unique users (set comprehension + a small parse helper)
def field(line, key):
    # returns the value of key=... or None
    for token in line.split():
        if token.startswith(key + "="):
            return token[len(key) + 1:]
    return None

users = {field(ln, "user") for ln in lines if field(ln, "user")}
print(users)
# 3. Level counts (dict comprehension over the known levels)
levels = ["INFO", "WARN", "ERROR"]
#counts = {lvl: sum(1 for ln in lines if lvl in ln) for lvl in levels}

# 4. Login failures — your turn: filter ERROR + action=login, collect (user, msg)

{'carol', 'alice', 'bob'}


**Stretch goals**

- Add a `--level` filter so the user can request just one level.
- Sort `unique users` with `sorted(...)` for stable output.
- Replace the eager lists with generators and measure the memory difference on a big synthetic log.

Notice how each of the four outputs naturally maps to a different comprehension type — list, set, dict, and a generator. That's the whole chapter in one project.

---

**Next up:** [Chapter 2: Iterators & Generators](chapter_02_iterators_generators/index.md)

---

<a id="ch2"></a>

# Chapter 2: Iterators & Generators

> *"Loops are how you walk a collection. Iterators are the legs that do the walking — and generators are legs that grow the path as you step on it."*

Most of us use `for` loops constantly without ever asking what they actually do. This chapter answers that. We'll rebuild the loop machinery by hand with `iter()` and `next()`, then meet generators — lazy functions that hand back values one at a time — and finally write the iterator protocol ourselves in a custom class.

Every code example here comes from a real student notebook (`advanced_python.ipynb`), with its real outputs and its real errors. I kept the bugs on purpose: a `StopIteration` from an exhausted iterator, a `NameError` from a non-existent `prev()`, and an infinite iterator. Each one is a way into a core idea.

---

<a id="ch2-learning-objectives"></a>

## Learning Objectives

By the end of this chapter you should be able to:

- Tell an **iterable** apart from an **iterator** and explain why the difference matters.
- Use `iter()` and `next()` by hand, and predict when `StopIteration` is raised.
- Explain what a `for` loop actually does (it's `iter()` + repeated `next()` + `StopIteration` handling).
- Write **generator functions** with `yield` and understand pausing and resuming.
- Say clearly how `yield` differs from `return`.
- Remember that generators (and iterators) are **forward-only / single-pass**.
- Implement the **iterator protocol** (`__iter__`, `__next__`) in a custom class and manage its state.
- Reason about **lazy evaluation** and **memory efficiency**, and choose a generator expression over a list comprehension when it matters.
- Spot iterators and generators in real code: file streaming, paginated APIs, ML data loaders, IoT/stock feeds, and `itertools` pipelines.

---

<a id="ch2-concept-explanation"></a>

## Concept Explanation

### Iterable vs Iterator — the distinction that matters most

These two words sound alike and get mixed up all the time. They are not the same thing.

| Term | What it is | How you get the other | Real example |
|------|-----------|----------------------|--------------|
| **Iterable** | An object you *can* loop over. It knows how to produce an iterator. | Call `iter(iterable)` to get an iterator. | `list`, `str`, `dict`, `set`, `range`, a file object |
| **Iterator** | An object that *does* the walking. It remembers where it is and hands you the next item when asked. | Call `next(iterator)` to advance it. | the object returned by `iter(my_list)` |

!!! note "The one-line rule"
    An **iterable** can be turned into an **iterator** with `iter()`. An **iterator** produces values with `next()` and remembers its position. Every iterator is also an iterable (calling `iter()` on an iterator returns itself), but not every iterable is an iterator.

#### Real-world intuition and visual analogies

Pick whichever analogy sticks for you — they all describe the same relationship:

- **Playlist (iterable) vs the "Now Playing" cursor (iterator).**
  The playlist is the collection of songs. The "Now Playing" cursor is the thing that knows which song is current and moves forward when you hit Next. You can create many cursors over one playlist, but each cursor tracks its own position.

- **Pez dispenser.**
  The dispenser is the iterator. Each time you press it (`next()`), one candy pops out and is gone for good. When it's empty, pressing again gives you nothing (`StopIteration`). You cannot put a candy back — there is no "previous."

- **Turnstile.**
  A turnstile only turns one way, one person at a time. You can't rewind it. Once everyone has passed through, it stops moving (the gate is exhausted).

The thread running through all three: forward-only, one item at a time, position is remembered, and once exhausted it's done.

#### Three levels of understanding

=== "Beginner"
    A `for` loop "just works" on lists, strings, and dicts. Behind the scenes Python turns the thing you're looping over into an **iterator** and pulls items off it one by one until there are none left.

=== "Intermediate"
    `iter(x)` gives you an iterator. `next(iterator)` returns the next item and moves the cursor forward. When there's nothing left, `next()` raises `StopIteration`. A `for` loop catches that exception silently and stops. You can do all of this by hand.

=== "Advanced"
    The **iterator protocol** is just two dunder methods: `__iter__` (returns the iterator object) and `__next__` (returns the next value or raises `StopIteration`). **Generators** are a language-level shortcut that builds an object implementing this protocol for you — `yield` saves and restores the function's entire execution state (local variables, instruction pointer) between calls. That's what makes lazy, memory-efficient streams so easy to write.

### The iterator protocol, formally

An object is an **iterator** if it implements:

- **`__iter__(self)`** — returns the iterator object itself (`return self`). This is what makes `iter(it)` work and lets the object be used directly in a `for` loop.
- **`__next__(self)`** — returns the next item, advancing internal state. When there are no more items, it must raise **`StopIteration`**.

An object is an **iterable** if it implements `__iter__` (which returns a *separate* iterator). Lists are iterables but not iterators — that's why you can loop over the same list twice.

### How a `for` loop really works

This is the mental model that ties the whole chapter together. When you write:

In [ ]:
# for item in collection:
#     do_something(item)

Python is actually doing roughly this:

In [ ]:
# _iterator = iter(collection)      # 1. get an iterator from the iterable
# while True:
#     try:
#         item = next(_iterator)    # 2. pull the next value
#     except StopIteration:
#         break                     # 3. exhausted? stop the loop
#     do_something(item)            # 4. run the loop body

Commit this to memory. Every "magic" `for` loop in Python is this `iter` + `next` + `StopIteration` dance.

```mermaid
sequenceDiagram
    participant For as for loop
    participant Iterable as Iterable (e.g. list)
    participant Iterator as Iterator (cursor)
    For->>Iterable: iter(collection)
    Iterable-->>Iterator: create & return iterator
    loop until StopIteration
        For->>Iterator: next(iterator)
        alt items remain
            Iterator-->>For: return next item
            Note over For: run loop body
        else exhausted
            Iterator--xFor: raise StopIteration
            Note over For: catch silently, break
        end
    end
```

```mermaid
flowchart TD
    A[Start for loop] --> B["iter(collection)<br/>get iterator"]
    B --> C["next(iterator)"]
    C --> D{StopIteration?}
    D -- No --> E[Run loop body with item]
    E --> C
    D -- Yes --> F[Stop loop / continue program]
```

---

<a id="ch2-iterators"></a>

## Iterators

Let's build the intuition by doing it manually — exactly the way the notebook did.

### Cell 1 — Turning a string into an iterator

#### Original Code

In [2]:
s='abcd'
it=iter(s)

while True:
    try:
        print(next(it))
    except StopIteration as e:
        print(e)
        break


a
b
c
d



#### What This Code Does

It takes a string (an **iterable**) and calls `iter()` on it to produce an **iterator** object. The last line just evaluates `it` so the notebook displays its `repr`.

#### Line-by-Line Breakdown

- `s='abcd'` — a 4-character string. Strings are iterables: you can loop over their characters.
- `it=iter(s)` — `iter()` asks the string for an iterator. We store that cursor in `it`.
- `it` — in a notebook, a bare expression echoes its representation, so we see the iterator object itself, not its contents.

#### Why This Output Occurs

`iter()` does not return the characters — it returns a cursor object that knows how to walk the string. The repr shows the type (`str_ascii_iterator`) and the memory address. No iteration has happened yet; the cursor is parked at the very first character, waiting for a `next()` call.

#### Common Mistakes

- Expecting `iter(s)` to print `a b c d`. It doesn't — it gives you the machine that produces them, not the values.
- Assuming the iterator "contains" a copy of the data. It doesn't; it references the original and tracks a position.

---

### Cell 2 — A lone `next()` that raised StopIteration

#### Original Code

In [ ]:
print(next(it))

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
StopIteration


#### What This Code Does

Asks the iterator for its next item. In a fresh iterator this would print `a`. But in the actual notebook session this line raised `StopIteration`.

#### Line-by-Line Breakdown

- `next(it)` — advance the cursor and return the value at the new position.
- `print(...)` — would display that value.

#### Why This Output Occurs

This is the most important teaching moment in the iterator section, and it's about notebook execution order, not a code bug.

By the time this cell ran, the iterator `it` had already been exhausted by earlier `next(it)` calls during interactive experimentation. An iterator is single-pass: once its cursor has walked off the end of `'abcd'`, there is nothing left. Calling `next()` on an exhausted iterator raises `StopIteration` — the iterator's way of saying "I'm empty, there is no next."

!!! warning "Notebooks lie about order"
    In a Jupyter notebook you can run cells in any order, and re-run them. The `[ ]` execution counter on the left shows the real order things happened — not top-to-bottom. A variable like `it` carries state across every cell that touches it. If an earlier run already consumed all of `it`, a later `next(it)` will raise `StopIteration` even though the cell looks like it should print `a`. When something surprises you in a notebook, check the execution counters and re-run from a clean kernel.

#### Common Mistakes

- Thinking `StopIteration` means "your code is broken." It usually just means "this iterator is used up." It's a normal, expected signal — `for` loops rely on it.
- Calling `next()` past the end in real code without handling the exception. Outside a notebook this crashes your program. Wrap it in `try/except` or use a `for` loop.
- Re-running the same iterator and expecting it to reset. Iterators don't reset — you make a fresh one with `iter()` again.

---

### Cell 3 — Safe iteration with `try`/`except`

#### Original Code

In [ ]:
while True:
    try:
        print(next(it))
    except StopIteration:
        break

a
b
c
d


#### What This Code Does

Drains an iterator safely: keep calling `next()` until it raises `StopIteration`, then stop. (This output assumes a fresh `it = iter('abcd')`.)

#### Line-by-Line Breakdown

- `while True:` — loop forever, until we explicitly break out.
- `try:` — attempt to fetch the next value.
- `print(next(it))` — advance the cursor and print the value.
- `except StopIteration:` — the moment the iterator is empty, this fires.
- `break` — exit the loop cleanly.

#### Why This Output Occurs

Each `next()` walks one character forward: `a`, then `b`, then `c`, then `d`. The fifth `next()` finds nothing left and raises `StopIteration`, which we catch and use to `break`. The output is the full string, one character per line.

!!! tip "You just wrote a `for` loop by hand"
    This `while True: try / next / except StopIteration: break` pattern is exactly what `for char in s:` does internally. The `for` statement is syntactic sugar over this exact loop. Once you see it, `for` loops stop being magic.

#### Common Mistakes

- Catching the wrong exception (e.g. bare `except:`), which can hide real bugs. Catch `StopIteration` specifically.
- Forgetting the `break` — that would loop forever once the exception stops firing (it always fires, so this is more a "wrong placement" risk).

---

### Cell 4 — Same pattern, now with a list

#### Original Code

In [ ]:
list1=[10,30,40,50]
it=iter(list1)
# ... next(it) repeatedly inside try/except ...
while True:
    try:
        print(next(it))
    except StopIteration:
        break

10
30
40
50


#### What This Code Does

Shows that the iterator protocol is universal — the identical loop works on a list with zero changes.

#### Line-by-Line Breakdown

- `list1=[10,30,40,50]` — a list (an iterable).
- `it=iter(list1)` — get a fresh iterator over the list.
- The `while True / try / next / except StopIteration / break` block — drains it safely, same as before.

#### Why This Output Occurs

`iter(list1)` returns a `list_iterator`. Each `next()` yields the next element in order; after `50` the next call raises `StopIteration` and we break. The type changed (string to list) but the protocol did not — that's the whole point.

!!! note "One protocol, every collection"
    Strings, lists, tuples, sets, dicts, files, `range`, generators — all of them speak the same `iter()`/`next()` language. Learn it once and you understand looping over everything in Python.

#### Common Mistakes

- Confusing the **list** (`list1`, reusable, an iterable) with the **iterator** (`it`, single-pass). You can `iter(list1)` again to get a brand-new cursor; you cannot rewind `it`.
- Modifying `list1` while iterating `it` — that can cause confusing skips or `RuntimeError`s. Don't mutate a collection mid-iteration.

---

<a id="ch2-generators"></a>

## Generators

A **generator** is, in the notebook's words, "a kind of function that returns an iterator object." Instead of building and returning a whole collection at once, a generator function uses `yield` to hand back one value at a time, pausing in between. It implements the iterator protocol automatically — you never write `__iter__`/`__next__` yourself.

### Cell 5 — Normal function vs generator function (and the `prev` bug)

#### Original Code

In [2]:
def get_number():            # normal function
    return [1,2,3,4,5]

def get_number_gen():        # generator function
    yield 1
    yield 2
    yield 3
    yield 4
    yield 5

nf=get_number()
print(nf)                    # prints the list

gf=get_number_gen()
print(prev(gf))              # BUG: prev() does not exist

[1, 2, 3, 4, 5]


NameError: name 'prev' is not defined

#### What This Code Does

Defines the same sequence of values two ways: a normal function that returns a list all at once, and a generator function that yields values lazily. Then it tries to read from the generator — using a function that doesn't exist.

#### Line-by-Line Breakdown

- `def get_number(): return [1,2,3,4,5]` — a normal function. Calling it builds the entire list in memory and hands it back.
- `def get_number_gen(): yield 1 ...` — the presence of **`yield`** makes this a generator function. Calling it does not run the body; it returns a generator object.
- `nf=get_number()` — `nf` is now the list `[1, 2, 3, 4, 5]`.
- `print(nf)` — prints the whole list.
- `gf=get_number_gen()` — `gf` is a generator object (paused at the top, nothing has run yet).
- `print(prev(gf))` — tries to call `prev()`. There is no built-in `prev()` in Python.

#### Why This Output Occurs

The first line, `print(nf)`, works fine — `get_number()` eagerly returns the list, so we see `[1, 2, 3, 4, 5]`.

The second line crashes with `NameError: name 'prev' is not defined`. This is a useful moment to slow down on:

!!! warning "There is no `prev()` — iterators only go forward"
    Python deliberately has no `prev()` function. Iterators and generators are forward-only and single-pass. You can ask for the next value (`next()`), but you can never ask for the previous one — the previous value is already gone, and the generator has not stored it. If you need to look back, you must remember it yourself (see the next example). The fix here is simply:

In [ ]:
print(next(gf))   # prints 1

Notice the asymmetry: the normal function gives you a list you can index, slice, and re-read freely (`nf[0]`, `nf[-1]`, loop twice). The generator gives you a one-way stream you consume once.

#### Common Mistakes

- Reaching for a non-existent `prev()` / `back()` / rewind. Use `next()` only; track history yourself if you need it.
- Expecting `gf = get_number_gen()` to run the function. It doesn't — calling a generator function just creates the generator. The body runs lazily, a `yield` at a time, only when you call `next()`.
- Trying to index or slice a generator (`gf[0]`) — generators are not subscriptable. Convert to a list first (`list(gf)`) if you truly need random access (but that defeats the memory savings).

---

### Cell 6 — Consuming the generator correctly

#### Original Code

In [3]:
while True:
    try:
        print(next(gf))
    except StopIteration:
        break

1
2
3
4
5


#### What This Code Does

Drains the generator the right way — using `next()` inside the same safe `try/except StopIteration` loop we used for iterators.

#### Line-by-Line Breakdown

- `next(gf)` — resume the generator until it hits the next `yield`, return that value, then pause again.
- `print(...)` — show each yielded value.
- `except StopIteration: break` — when the generator function returns (reaches the end), `next()` raises `StopIteration`; we catch it and stop.

#### Why This Output Occurs

Each `next(gf)` un-pauses the function, runs it forward to the next `yield`, and freezes it again — handing back `1`, then `2`, and so on through `5`. After `yield 5`, the next resume reaches the end of the function, so the generator raises `StopIteration` and the loop breaks.

!!! note "Generators ARE iterators"
    Because `gf` is an iterator, this is the identical pattern as the string/list cells. And just like those, you could write `for n in gf: print(n)` and Python would do this loop for you. A generator is the easiest way there is to create an iterator.

#### Common Mistakes

- Trying to consume `gf` twice. After this loop, `gf` is exhausted — looping again prints nothing. Generators are single-pass; call `get_number_gen()` again for a fresh one.
- Forgetting that the function body only advances on `next()`. Side effects inside the generator (prints, DB writes) happen lazily, not when you create the generator.

---

### Cell 7 — Tracking previous & current manually (the sliding window)

#### Original Code

In [4]:
def my_generator():
    yield 10
    yield 20
    yield 30

gen = my_generator()
prev_value = None
current_value = next(gen)
try:
    while True:
        next_value = next(gen)
        print(f"Previous: {prev_value}, Current: {current_value}")
        prev_value = current_value
        current_value = next_value
except StopIteration:
    print(f"Reached end. Last value was {current_value}")

Previous: None, Current: 10
Previous: 10, Current: 20
Reached end. Last value was 30


#### What This Code Does

Since a generator can't go backward, this code manually remembers the previous value while walking forward — the classic sliding-window pattern over a one-pass stream.

#### Line-by-Line Breakdown

- `gen = my_generator()` — create the generator (yields 10, 20, 30).
- `prev_value = None` — there is no value before the first one.
- `current_value = next(gen)` — pull the first value (`10`) and call it "current."
- `while True:` — loop until the stream runs out.
- `next_value = next(gen)` — peek ahead at the value after current. This is the call that can raise `StopIteration` when we run off the end.
- `print(f"Previous: {prev_value}, Current: {current_value}")` — report the window we currently hold.
- `prev_value = current_value` — slide: today's current becomes tomorrow's previous.
- `current_value = next_value` — slide: the peeked value becomes the new current.
- `except StopIteration:` — when `next(gen)` runs out, print the final value we were holding.

#### Why This Output Occurs

Walk the state machine:

| Step | `prev_value` | `current_value` | `next_value = next(gen)` | Printed |
|------|-------------|-----------------|--------------------------|---------|
| init | `None` | `10` | — | — |
| loop 1 | `None` | `10` | `20` | `Previous: None, Current: 10` |
| loop 2 | `10` | `20` | `30` | `Previous: 10, Current: 20` |
| loop 3 | `20` | `30` | `StopIteration` | (jumps to except) |
| except | — | `30` | — | `Reached end. Last value was 30` |

Here's the subtlety to catch: `Current: 30` is never printed inside the loop. Each loop iteration first tries to fetch the next value (`next_value = next(gen)`) and only then prints. When `current_value` is `30`, the `next(gen)` call at the top of the loop body raises `StopIteration` before the `print` runs — so control jumps straight to the `except` block. The final value reappears there as "Last value was 30."

!!! tip "The look-ahead trap"
    Whenever you peek ahead at the start of a loop body, the last item gets special treatment: the body never completes for it because the look-ahead fails first. Handling that final item in the `except` block is the standard fix — and exactly why this example puts the closing message there.

#### Common Mistakes

- Putting the `print` after `next_value = next(gen)` and then being surprised the last item is missing from the loop — that's by design here; handle it in `except`.
- Assuming you can rewind to get `prev_value` from the generator itself. You can't; you must store it yourself, which is the entire point of this example.

---

### yield vs return

The notebook's notes on this were a bit scattered, so here's the clean version.

| Aspect | `return` | `yield` |
|--------|----------|---------|
| Effect on the function | **Ends** it. Control leaves for good. | **Pauses** it. State (locals + position) is saved and resumed on the next `next()`. |
| How many values | Produces everything **at once** (e.g. a full list). | Produces values **one at a time** (lazy). |
| Memory | Holds the whole result in memory. | Holds only the current item. |
| Return type | Whatever you return (list, dict, int…). | A **generator** (an iterator). |
| Re-entry | A function runs from the top every call. | A generator *resumes* where it paused. |
| Use when | The result is small and you need it all / want random access. | The data is large, infinite, or streamed; you process one item at a time. |

In [12]:
# return: eager, all-at-once, re-readable
def squares_list(n):
    return [x*x for x in range(n)]   # builds the whole list NOW

# yield: lazy, one-at-a-time, single-pass
def squares_gen(n):
    
    for x in range(n):
        yield x*x
                        # produces each square only when asked

square_num = squares_gen(5)

print(next(square_num))
print(next(square_num))
print(next(square_num))


0
1
4


!!! note "A function with even one `yield` is a generator function"
    The moment Python sees `yield` anywhere in a function body, the function becomes a generator function. Calling it returns a generator object and runs none of the body until you start pulling values.

Where generators earn their keep in practice: reading large files line by line, data streaming (real-time IoT sensors, NEPSE stock feeds), training ML models in batches, and video/audio inference where frames or samples arrive one at a time.

---

<a id="ch2-building-a-custom-iterator-the-protocol"></a>

## Building a Custom Iterator (the protocol)

Generators write the iterator protocol for you. To really understand it, let's implement it by hand with a class — exactly as the notebook did.

### Cell 8 — A `Number` iterator and its mutating state

#### Original Code

In [ ]:
class Number:
    def __iter__(self):
        self.n=2
        return self
    def __next__(self):
        x=self.n
        self.n+=2
        return x

even=Number()
print(even.__dict__)   # {} before iteration
it=iter(even)
print(next(it))        # 2
print(even.__dict__)   # {'n': 4}

{}
2
{'n': 4}


#### What This Code Does

Defines a class that is its own iterator: `__iter__` initializes the state and returns `self`; `__next__` produces the next even number and advances. The `__dict__` prints let us watch the internal state mutate.

#### Line-by-Line Breakdown

- `class Number:` — our custom iterable and iterator.
- `def __iter__(self):` — called by `iter()`. It sets `self.n = 2` (the starting state) and returns `self`, meaning this very object is the iterator.
- `def __next__(self):` — called by `next()`. It grabs the current `self.n` into `x`, increments `self.n` by 2, and returns `x` (the value before incrementing).
- `even=Number()` — create an instance. At this point `__iter__` has not run, so there is no `n` attribute yet.
- `print(even.__dict__)` — an object's `__dict__` shows its instance attributes. It's empty `{}` because `n` doesn't exist until `__iter__` runs.
- `it=iter(even)` — triggers `__iter__`, which sets `self.n = 2` and returns the object. Now `even` has `n`.
- `print(next(it))` — triggers `__next__`: `x = 2`, then `n` becomes `4`, returns `2`.
- `print(even.__dict__)` — now shows `{'n': 4}` (the state after one advance).

#### Why This Output Occurs

- `{}` — before `iter()`, no instance attribute `n` exists, so `__dict__` is empty.
- `2` — `__next__` returns the value of `n` before incrementing (`x = self.n` = 2), then sets `n = 4`.
- `{'n': 4}` — confirms the side effect: the object now stores `n = 4`, ready to yield `4` on the next call.

This is the protocol made visible. `__iter__` initializes state; `__next__` reads, then advances state. The object literally carries its position inside `self.n`.

#### Common Mistakes

- Putting the state reset in `__init__` instead of `__iter__`, then being surprised that you can't restart iteration. Resetting in `__iter__` means each `for`/`iter()` starts fresh.
- Incrementing before reading (`self.n += 2; return self.n`) — that would skip the first value. Read into `x` first, then advance.
- Forgetting `return self` in `__iter__`. Without it, `iter(even)` returns `None` and `next()` blows up.

---

### Cell 9 — The state keeps mutating (and the infinite-iterator danger)

#### Original Code

In [ ]:
print("-"*50)
print(even.__dict__)   # {'n': 10}  (after several next() calls)
print(next(it))        # 10

--------------------------------------------------
{'n': 10}
10


#### What This Code Does

After several more `next(it)` calls during experimentation, this confirms the state has advanced to `n = 10`, then pulls one more value.

#### Line-by-Line Breakdown

- `print("-"*50)` — prints a 50-character separator line (`"-"` repeated 50 times). Just a visual divider.
- `print(even.__dict__)` — shows the current internal state. By now `n` has climbed to `10` from earlier `next()` calls.
- `print(next(it))` — `__next__` returns `10` (the current `n`), then bumps `n` to `12`.

#### Why This Output Occurs

Each earlier `next()` added 2 to `n`, so the state has marched `4 → 6 → 8 → 10`. The `__dict__` snapshot shows `{'n': 10}`, and the following `next()` returns that `10` (then sets `n = 12`). The separator is simply `"-" * 50`.

!!! danger "This iterator is INFINITE — it never raises StopIteration"
    Look closely at `__next__`: there is no stopping condition. It will happily return `2, 4, 6, 8, …` forever. That's fine when you pull values manually with `next()`, but it is dangerous with a `for` loop:

In [13]:
for x in Number():   # NEVER STOPS — infinite loop, your program hangs
    print(x)

NameError: name 'Number' is not defined

    A well-behaved iterator must eventually raise `StopIteration` so loops can terminate. To make `Number` safe, add a limit:

In [14]:
class Number:
    def __init__(self, limit):
        self.limit = limit
    def __iter__(self):
        self.n = 2
        return self
    def __next__(self):
        if self.n > self.limit:      # stopping condition
            raise StopIteration
        x = self.n
        self.n += 2
        return x

print(list(Number(10)))   # [2, 4, 6, 8, 10]

[2, 4, 6, 8, 10]


#### Common Mistakes

- Looping over an unbounded iterator with `for` (infinite hang). Either add a `StopIteration` condition or guard with `itertools.islice`/a counter.
- Sharing one instance across multiple loops without re-`iter()`-ing — state leaks between loops because the position lives in `self.n`. (Generators avoid this by creating fresh objects each call.)
- Forgetting that this design makes the object both iterable and iterator (returns `self`), so two simultaneous loops would clobber each other's position.

---

<a id="ch2-lazy-evaluation-memory"></a>

## Lazy Evaluation & Memory

This is the practical payoff of everything above.

**Eager** evaluation (a normal function, a list comprehension) computes and stores all results immediately. **Lazy** evaluation (a generator, a generator expression) computes each result only when asked, holding just one item at a time.

### List comprehension (eager) vs generator expression (lazy)

The syntax difference is tiny — `[]` vs `()` — but the behavior is night and day:

In [ ]:
nums = [x * x for x in range(1_000_000)]   # LIST: builds 1,000,000 ints in memory NOW
nums = (x * x for x in range(1_000_000))   # GENERATOR: builds nothing yet; yields lazily

- `[ ... ]` gives a **list**. Eager. All million squares materialized up front. Re-readable, indexable, slow to start, memory-hungry.
- `( ... )` gives a **generator**. Lazy. Computes each square on demand, holds one at a time. Single-pass, not indexable, instant to create, tiny memory footprint.

!!! tip "Callback to Chapter 1"
    We first touched on generator expressions in the comprehensions chapter — see [`chapter_01_comprehensions/index.md`](chapter_01_comprehensions/index.md). Now you know why swapping `[]` for `()` matters: it turns an eager list into a lazy, memory-efficient generator that plugs straight into the iterator protocol you've just learned.

### Memory difference (illustrative)

The numbers below are representative and illustrative — they show the order of magnitude, not exact figures from your machine. Run it yourself with `sys.getsizeof` to confirm the gap.

In [4]:
import sys

list_version = [x * x for x in range(1_000_000)]   # eager
gen_version  = (x * x for x in range(1_000_000))   # lazy

print(sys.getsizeof(list_version))   # ~8,000,000+ bytes  (≈ 8 MB) — grows with N
print(sys.getsizeof(gen_version))    # ~200 bytes (illustrative) — CONSTANT, independent of N

8448728
208


```text
8448728      # the list: millions of bytes, scales with the number of items
200          # the generator: a couple hundred bytes, no matter how big N is
```

!!! note "Why the generator is tiny"
    The list physically stores a million integers. The generator stores only the recipe (the loop plus the expression) and the current position — a few hundred bytes that stay constant whether you iterate over a thousand items or a billion. That's the whole reason generators exist: process streams larger than RAM, one item at a time.

Rule of thumb: if you only need to walk the data once and the data is large (or infinite, or arriving over time), use a generator. If you need to re-read, index/slice, or the data is small, a list is fine.

---

<a id="ch2-real-industry-usage"></a>

## Real Industry Usage

Iterators and generators turn up all over production Python:

- **Reading huge files line by line.** A file object is already an iterator. `for line in open("huge.log"):` streams one line at a time and never loads the whole (possibly multi-GB) file into memory. The same pattern powers log processors and ETL jobs.

- **Streaming APIs and pagination.** A generator that fetches page after page (`while next_url: yield items; next_url = resp.next`) lets callers iterate over all records as if they were one list, while only one page is in memory at a time. This is how SDKs expose "auto-paginating" iterators.

- **ML data loaders and batching.** PyTorch's `DataLoader` is an iterable that yields batches of training data lazily — you never hold the entire dataset in RAM. `for batch in dataloader:` pulls and (optionally) preprocesses each batch on demand, often across worker processes.

- **Real-time sensor/IoT and stock feeds.** IoT sensor streams and live market feeds like NEPSE are naturally infinite generators: each `next()` is the next reading or tick. You process events as they arrive instead of waiting for a (never-ending) "complete" dataset.

- **Built-ins are already lazy.** `range`, `zip`, `enumerate`, `map`, and `filter` all return lazy iterators in Python 3 — they don't build lists. That's why `range(10**9)` is instant and memory-free. Wrap them in `list()` only when you actually need the materialized result.

- **Pipelines with `itertools`.** The `itertools` module (`islice`, `chain`, `groupby`, `count`, `tee`, `takewhile`…) lets you compose lazy data pipelines that stay memory-efficient end to end — read, filter, transform, batch, all one item at a time.

---

<a id="ch2-quick-recap"></a>

## Quick Recap

- An **iterable** can be turned into an **iterator** with `iter()`; an **iterator** produces values with `next()` and remembers its position.
- `next()` on an exhausted iterator raises **`StopIteration`** — a normal signal, not a bug.
- A `for` loop is `iter()` + repeated `next()` + silent `StopIteration` handling.
- Iterators and generators are forward-only and single-pass — there is no `prev()`; track history yourself if needed.
- A function with **`yield`** is a generator function: calling it returns a generator that pauses and resumes, producing one value at a time.
- `return` ends a function and produces everything at once; `yield` pauses it and produces values lazily.
- The iterator protocol is `__iter__` (init state, return the iterator) plus `__next__` (return next value, advance, raise `StopIteration` when done).
- A custom iterator with no stopping condition is infinite — deadly in a `for` loop.
- Generators give you lazy evaluation and constant memory — swap `[ ]` for `( )` to go from eager list to lazy generator.

---

<a id="ch2-interview-questions"></a>

## Interview Questions

### Beginner

??? note "What is the difference between an iterable and an iterator?"
    An **iterable** is any object you can loop over (list, str, dict, range…); it implements `__iter__` and produces a *fresh* iterator when you call `iter()` on it. An **iterator** is the object that actually walks the data: it implements `__next__`, remembers its current position, and raises `StopIteration` when exhausted. Every iterator is also an iterable (its `__iter__` returns itself), but most iterables (like lists) are **not** iterators — which is why you can loop over a list many times.

??? note "What does the `yield` keyword do?"
    `yield` turns a function into a **generator function**. When the function hits `yield`, it **pauses**, saving all local state and its position, and hands the yielded value back to the caller. On the next `next()` call it **resumes** right after the `yield`. This produces values lazily, one at a time, instead of computing and returning them all at once.

??? note "What does `StopIteration` mean, and when is it raised?"
    `StopIteration` is the iterator's signal that it has **no more items**. It is raised by `next()` when the iterator is exhausted, and by a generator function when it reaches its end (or hits `return`). `for` loops catch it silently to know when to stop. It is an expected control-flow signal, not an error in your logic.

### Intermediate

??? note "How does a `for` loop work internally?"
    Python calls `iter()` on the iterable to get an iterator, then repeatedly calls `next()` on that iterator, running the loop body for each returned value. When `next()` raises `StopIteration`, the loop catches it silently and stops. Concretely it's: `it = iter(obj); while True: try: x = next(it) except StopIteration: break; <body>`.

??? note "What's the difference between a generator and a list (and when would you choose each)?"
    A **list** is eager: it builds and stores every element up front, is re-readable, and supports indexing/slicing — but uses memory proportional to its size. A **generator** is lazy: it produces one element at a time, uses constant memory, but is single-pass and not indexable. Choose a list for small data you need to re-read or random-access; choose a generator for large/infinite/streamed data you process once.

??? note "Generator expression vs list comprehension — what's the memory impact?"
    `[x for x in it]` (square brackets) builds a **full list** in memory immediately (eager) — memory grows with the number of items. `(x for x in it)` (parentheses) builds a **generator** that computes each value on demand (lazy) — memory stays roughly **constant** regardless of size. For large datasets the generator expression can use kilobytes where the list uses gigabytes.

### Advanced

??? note "Can you reuse an exhausted generator (or iterator)? Why or why not?"
    **No.** Generators and iterators are **single-pass**. Once exhausted, every further `next()` immediately raises `StopIteration`, and a `for` loop over it produces nothing. There is no reset — the internal position has run off the end and the generator's frame is finished. To iterate again you must create a **new** one (call the generator function again, or `iter()` the original *iterable* again). If you genuinely need multiple passes, materialize the data into a list, or use `itertools.tee` (with care about its buffering).

??? note "How do you implement the iterator protocol in a custom class?"
    Implement two dunder methods. `__iter__(self)` initializes state and returns the iterator object (usually `return self`). `__next__(self)` returns the next value while advancing internal state, and **raises `StopIteration`** when there are no more values. Without a `StopIteration` condition the iterator is infinite and will hang any `for` loop. Resetting state in `__iter__` (not `__init__`) lets each new iteration start fresh.

??? note "Why is there no `prev()` in Python, and what do you do if you need the previous value?"
    Iterators are designed to be **forward-only** so they can stream data they don't fully hold in memory (files, network, infinite sequences) — storing every past value would defeat that purpose. So Python deliberately offers only `next()`. If you need to look back, **you** must remember previous values yourself (e.g. keep a `prev_value` variable, as in the sliding-window example) or buffer a window with something like `collections.deque(maxlen=k)`.

---

<a id="ch2-practice-exercises"></a>

## Practice Exercises

**Easy**

1. Create a list `[5, 10, 15, 20]`, get an iterator with `iter()`, and print every element using **only** `next()` inside a `try/except StopIteration` loop (no `for`).
2. Write a generator function `count_up(n)` that yields `1, 2, …, n`. Consume it with a `for` loop and print each value.

**Medium**

3. Write a generator `even_numbers(limit)` that yields even numbers `2, 4, …` up to (and not exceeding) `limit`. Test it with `list(even_numbers(10))` → `[2, 4, 6, 8, 10]`.
4. Given a list of numbers, build **both** a list comprehension and a generator expression of their squares. Use `sys.getsizeof` on each and print the two sizes side by side. Explain the difference in a comment.
5. Rewrite the `my_generator` sliding-window example so it stores the **previous, current, and next** values (a 3-wide window) and prints them, handling the start and end edges cleanly.

**Hard**

6. Make the `Number` class from this chapter **safe**: add a `limit` so it raises `StopIteration` once it passes the limit, then verify `list(Number(20))` terminates correctly.
7. Write a generator `read_chunks(path, n)` that reads a text file and yields it `n` lines at a time (a "batch" of lines). Process a multi-line file without ever holding the whole file in memory.

---

<a id="ch2-challenge-project"></a>

## Challenge Project

### Memory-Efficient Log/CSV Processor + Infinite Number Generator

Build a small toolkit that proves you understand lazy evaluation.

**Part A — Streaming log processor**

Write a pipeline of generators that processes a large log/CSV file one line at a time (never loading it all into memory):

1. `read_lines(path)` — a generator that yields lines from the file lazily.
2. `parse(lines)` — a generator that takes the line stream and yields parsed records (e.g. split CSV into a dict, or extract fields from a log line).
3. `only_errors(records)` — a generator that yields only records matching some condition (e.g. `level == "ERROR"`).
4. Chain them: `for rec in only_errors(parse(read_lines("app.log"))): print(rec)`.

**Part B — Infinite generator + `take(n)` helper**

1. Write an **infinite** generator `fibonacci()` (or `primes()`) that yields values forever.
2. Write a helper `take(gen, n)` that returns the first `n` values from *any* iterator/generator (hint: loop `n` times calling `next()`, or use `itertools.islice`).
3. Demonstrate: `print(take(fibonacci(), 10))` → `[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]`.

!!! tip "Hints"
    - For Part A, each stage should receive an iterator and yield — that's what makes the pipeline lazy end to end. No stage builds a full list.
    - `itertools.islice(gen, n)` is the idiomatic `take`. Implementing it by hand with `next()` in a `try/except StopIteration` loop is good protocol practice.
    - Your infinite generator must not have a stop condition inside it — the *consumer* (`take`/`islice`) decides when to stop. This is the safe way to use an infinite iterator.
    - Bonus: add `take_while(gen, predicate)` that yields until the predicate becomes false (compare with `itertools.takewhile`).

**Success criteria:** the log processor handles a file far larger than RAM without crashing, and `take(fibonacci(), 1_000_000)` returns quickly while using constant memory per step.

---

Previous: [`chapter_01_comprehensions/index]

Next up: [`chapter_03_functional_programming/index]

---

In [ ]:
# Easy 1

list_nums = [5,10,15,20]

list_iterator = iter(list_nums) # Object creation 

try:
    for i in range(6):
        print(next(list_iterator))
except StopIteration as e:
    print(f"StopIteration occured!!")
    print(e)


5
10
15
20
StopIteration occured!!



In [28]:
# Easy 2
def count_up(n):
    for i in range(n):
        yield i

count = 10
num = count_up(count)

for i in range(10):
    print(next(num))




0
1
2
3
4
5
6
7
8
9


In [5]:
# Medium 3
def even_numbers(limit):
    i = 2
    while i <= limit:
        yield i + 2
        i = i + 2


print(list(even_numbers(10)))


[4, 6, 8, 10, 12]


In [ ]:
# Medium 4

import sys

sqr_list = [ i * 2 for i in range(1_000_000)]

sqr_generator = (a * 2 for a in range(1_000_000))

print("size of list: ", sys.getsizeof(sqr_list))
print("size of generator: ", sys.getsizeof(sqr_generator))
print(next(sqr_generator))

# size of list: 8448728
# size of generator: 208

# so the answer is if we use less number in the range 
# we get size of list way smaller then that of generator 
# as the generator has to store multiple things along with current value 

# Basically what I am trying to say is when using list it retrives all 
# values and stores it in the memory 

# But in the generator it remains constant and the values only one value 
# a time and works same as the concept like we use the iter() and next()



size of list:  8448728
size of generator:  208
0


In [ ]:
# Medium 5
def my_generator():
    yield 10
    yield 20
    yield 30

gen = my_generator()
prev_value = None
current_value = None
next_value = None

try:
    while True:
        next_val = next(gen)
        if next_value != None:
            if current_value != None:
                prev_value = current_value
            current_value = next_value
        next_value = next_val
        print(f"Previous: {prev_value}, Current: {current_value},Next: {next_value}")

except StopIteration as e:
    prev_value = current_value
    current_value = next_value
    next_value = None
    print(f"Previous: {prev_value}, Current: {current_value},Next: {next_value}")
    print(f"Reached end. Last value was {current_value}")

Previous: None, Current: None,Next: 10
Previous: None, Current: 10,Next: 20
Previous: 10, Current: 20,Next: 30
Previous: 20, Current: 30,Next: None
Reached end. Last value was 30


In [8]:
# Hard 6
class Number:
    def __init__(self,limit):
        self.limit = limit
        self.i = 0

    def __iter__(self):
        return self

    def __next__(self):
        if self.i <= self.limit:
            self.i +=1
            return self.i

        raise StopIteration
        

print(list(Number(20)))



[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]


In [ ]:
# Memory Efficient log/CSV Processor + Infinite Number Generator

# Part A

# Streaming log processor

<a id="ch3"></a>

# Chapter 3: Functional Programming

> Higher-Order Functions, `lambda`, and the built-in trio `map` / `filter` / `reduce` (plus `sorted`).

This chapter is about treating **functions as data** — values you can store in variables, pass into other functions, and return from functions. Once that clicks, a lot of code gets shorter and more declarative. It's also the idea behind data pipelines, AI agent tool-routing, callbacks, and the strategy pattern.

---

<a id="ch3-learning-objectives"></a>

## Learning Objectives

By the end of this chapter you will be able to:

- Explain what it means that **functions are first-class objects** in Python.
- Distinguish **referencing** a function (`greet`) from **calling** it (`greet('ram')`) — and fix the `TypeError: 'NoneType' object is not callable` bug that comes from confusing the two.
- Write and reason about **higher-order functions** (functions that take or return functions).
- Refactor an ugly `if/elif` dispatcher into a clean **function-dispatch** design — the same pattern AI agents use to route to "tools".
- Write **`lambda`** expressions, understand the *one-expression* rule, and use **ternary expressions** inside them.
- Use **`map`**, **`filter`**, **`reduce`**, and **`sorted`** confidently, including the `key=` argument.
- Know when a **list comprehension** is the more Pythonic choice over `map`/`filter`.
- Recognize where functional programming shows up in **industry** (pandas `.apply`, Spark/MapReduce, callbacks, sorting records).

---

<a id="ch3-concept-explanation"></a>

## Concept Explanation

### Functions are first-class objects

In Python, a function is just an **object** — the same way an `int`, a `str`, or a `list` is an object. So anything you can do with an ordinary value, you can do with a function:

- **Assign** it to a variable: `f = greet`
- **Store** it in a list or dict: `tools = [search_tool, sql_tool]`
- **Pass** it as an argument: `execute(greet, "Ram")`
- **Return** it from another function.

A **higher-order function** falls right out of that:

> A higher-order function takes a function as an argument **and/or** returns a function as a result.

#### Beginner intuition

You already know how to *use* functions: you call them. The new skill is *handing them around* without calling them. `greet` is the recipe; `greet('ram')` is actually cooking the meal. You can give someone the recipe (the function) so they can cook later, or you can give them the finished meal (the return value). Those are two different things.

#### Intermediate intuition

Because functions are values, you can build **tables of behavior** (a dict of functions) and **pipelines of transformations** (map → filter → reduce). Instead of spelling out *how* to loop, you describe *what* transformation to apply and let `map`/`filter`/`reduce` do the looping. That's the **declarative** style.

#### Advanced intuition

First-class functions plus closures (Chapter 5) give you decorators, partial application, currying, callbacks, and the strategy pattern — none of which require classes. Functional composition lets you view a program as data flowing through a series of pure transformations, which tends to be easier to test, parallelize (think Spark), and reason about.

#### Real-world intuition

- A **spreadsheet** column transformation ("apply this formula to every row") is `map`.
- A **filter** in a search UI ("show only items where price < 50") is `filter`.
- A **running total or aggregate** ("sum all sales") is `reduce`.
- A **sort by column** ("order employees by salary") is `sorted(..., key=...)`.

#### Visual analogy: a function is a "verb you can hand to someone"

Most values are nouns — `5`, `"Ram"`, `[1,2,3]`. A function is a **verb** ("greet", "square", "send_email"). First-class functions mean you can put that verb in an envelope and hand it to another part of your program, which then decides *when* and *with what* to perform the action.

### The functional data pipeline

Functional code often reads as **data flowing through stages**: take some data, transform each item (`map`), keep only what you want (`filter`), then collapse it to a single result (`reduce`).

```mermaid
flowchart LR
    data["data<br/>(iterable)"] --> map["map<br/>transform each item"]
    map --> filter["filter<br/>keep matching items"]
    filter --> reduce["reduce<br/>fold to one value"]
    reduce --> result["result"]
```

!!! note "Order is flexible"
    You don't always use all four, and the order can change (for example, filter *before* map to avoid transforming items you'll throw away). The pipeline above is the standard mental model, not a rule you have to follow.

---

<a id="ch3-higher-order-functions"></a>

## Higher-Order Functions

### Referencing vs. calling a function (the classic bug)

This is the distinction to nail down in this chapter. Miss it and you'll get confusing `NoneType` errors.

#### Original Code

In [ ]:
def greet(name):
    print("hello")

say_hello=greet('ram')   # greet RUNS here, returns None
say_hello()              # fails: None is not callable

hello
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'NoneType' object is not callable


#### What This Code Does

It *means* to store the function `greet` so it can be called later. But it accidentally **calls** `greet` right away and stores its **return value** instead of the function itself.

#### Line-by-Line Breakdown

| Line | What happens |
|------|--------------|
| `def greet(name):` | Defines a function. `greet` is now a function object. |
| `print("hello")` | The body — it prints, but has **no `return`**, so `greet` returns `None`. |
| `say_hello = greet('ram')` | The `(...)` **calls** `greet` right now. It prints `hello` and returns `None`. `say_hello` is now `None`, *not* the function. |
| `say_hello()` | Tries to call `None`. `None` is not callable, so you get a `TypeError`. |

(The notebook only showed `hello`, because the error happens on the *next* line, `say_hello()`.)

#### Why This Output Occurs

`greet('ram')` is **evaluated immediately**, and two things happen:
1. The side effect `print("hello")` runs, so we see `hello`.
2. There's no `return`, so the expression's value is `None`.

So `say_hello = None`. When you then write `say_hello()`, Python tries to invoke `None` like a function and refuses.

The fix is to **reference** the function (no parentheses) when you want to store it for later:

In [ ]:
say_hello = greet        # store the function object (no call yet)
say_hello('ram')         # now call it -> prints "hello"

#### Common Mistakes

- **Adding `()` when you meant to pass or store the function.** `greet` is the verb; `greet('ram')` is the verb already performed.
- **Forgetting `return`.** A function with only `print` returns `None`. Printing is *displaying*; returning is *handing back a value* you can reuse.
- **Rule of thumb:** parentheses mean "do it now." No parentheses means "here's the function, do it later."

---

### A higher-order function that takes a function

#### Original Code

In [ ]:
def greet(name):
    return f"hello {name}"

def execute(greet,abc):   # higher-order function: takes a function
    return greet(abc)

execute(greet,"Ram")

'hello Ram'


#### What This Code Does

`execute` accepts a **function** (its first parameter) and a **value**, then calls the function with the value and returns the result. That's a higher-order function in its simplest form.

#### Line-by-Line Breakdown

| Line | What happens |
|------|--------------|
| `def greet(name): return f"hello {name}"` | A normal function that *returns* a greeting (note: now it returns, unlike the buggy version above). |
| `def execute(greet, abc):` | `execute` takes a function as `greet` and a value as `abc`. The parameter name `greet` is local — it shadows the outer `greet` *inside* this function. |
| `return greet(abc)` | Calls whatever function was passed in, with `abc`. |
| `execute(greet, "Ram")` | Passes the **function object** `greet` (no parentheses) and the string `"Ram"`. |

#### Why This Output Occurs

We hand `execute` the function `greet` (referenced, not called) plus `"Ram"`. Inside, `greet("Ram")` returns `"hello Ram"`, which `execute` returns.

#### Common Mistakes

- Naming the parameter `greet` works but is confusing, because it shadows the global `greet`. A generic name like `func` or `task_function` reads better.
- Writing `execute(greet("Ram"))` — that calls `greet` first and passes a *string* where a *function* is expected.

---

### Dispatch the ugly way: `if/elif`

#### Original Code

In [ ]:
def send_email(message): print(f"sending email: {message}")
def send_sms(message): print(f"sending sms: {message}")
def send_notification(message): print(f"sending notification: {message}")

task='email'
if task=="email":
    send_email("email server is down")
elif task=="sms":
    send_sms("sms server is down")
elif task=='notification':
    send_notification("notification server is down")

sending email: email server is down


#### What This Code Does

Chooses which "send" function to run based on the string in `task`, using a chain of `if/elif`.

#### Line-by-Line Breakdown

| Line | What happens |
|------|--------------|
| `def send_email/sms/notification(...)` | Three functions, each printing a message. |
| `task = 'email'` | The selector that decides which branch runs. |
| `if task=="email": ...` | Matches, so `send_email(...)` runs. The other branches are skipped. |

#### Why This Output Occurs

`task` equals `"email"`, so only the first branch executes. The `elif` branches never run.

#### Common Mistakes

- **It doesn't scale.** Ten task types means ten branches. Every new tool means editing this chain.
- It's easy to mistype a branch or forget one, and hard to test each branch on its own.

---

### Dispatch the clean way: pass the function

#### Original Code

In [ ]:
def execute(task_function,value):
    task_function(value)

execute(send_email,"email server is down")
execute(send_sms,"sms server is down")

sending email: email server is down
sending sms: sms server is down


#### What This Code Does

Instead of `if/elif`, we **pass the chosen function** directly to a generic `execute`. The decision lives at the call site; `execute` stays small and doesn't change.

#### Line-by-Line Breakdown

| Line | What happens |
|------|--------------|
| `def execute(task_function, value):` | Higher-order function: `task_function` is a function. |
| `task_function(value)` | Calls whatever was passed, with `value`. |
| `execute(send_email, "...")` | Hands over the `send_email` function object plus a message. |
| `execute(send_sms, "...")` | Same, with `send_sms`. |

#### Why This Output Occurs

Each `execute(...)` call invokes the passed function with the message. No branching needed — the caller already decided which function to use.

#### Common Mistakes

- Passing `send_email("...")` instead of `send_email` — that calls it too early and passes the **return value** (`None`) into `execute`.
- For many tasks, store functions in a **dispatch dictionary**: `tools = {"email": send_email, "sms": send_sms}`, then `tools[task](msg)`. That replaces the whole `if/elif` chain with one lookup.

---

### Real-world flavor: AI agent "tool dispatch"

#### Original Code

In [ ]:
def search_tool(query): return f"searching : {query}"
def sql_tool(query): return f"running sql : {query}"
def weather_tool(query): return f"getting weather: {query}"

def execute_tool(tool,query):
    return tool(query)

execute_tool(search_tool,"give me the summary of attention is all you need")

'searching : give me the summary of attention is all you need'


#### What This Code Does

This mirrors how an **LLM or AI agent** routes a request to a "tool". Each tool is a function, and a generic `execute_tool` runs whichever tool was selected.

#### Line-by-Line Breakdown

| Line | What happens |
|------|--------------|
| `def search_tool/sql_tool/weather_tool(query):` | Three "tools", each returning a string describing what it would do. |
| `def execute_tool(tool, query):` | Higher-order dispatcher. |
| `return tool(query)` | Calls the chosen tool with the query. |
| `execute_tool(search_tool, "...")` | Routes to the search tool. |

#### Why This Output Occurs

`search_tool` is passed (referenced, not called) and invoked inside `execute_tool` with the query, returning the `"searching : ..."` string.

#### Why this matters

Modern AI agents work this way: the model picks a tool name, and a dispatcher maps that name to a Python function and calls it. In practice this is usually a **dict of tools** (`{"search": search_tool, ...}`), so adding a new capability is just adding one entry — no `if/elif` surgery.

#### Common Mistakes

- Hard-coding tool selection with `if/elif` instead of a dispatch table — it doesn't scale as the number of tools grows.

---

<a id="ch3-lambda-functions"></a>

## Lambda Functions

A **lambda** is a small **anonymous** function: any number of arguments, but only **ONE expression** (no statements, no multiple lines).

**Syntax:** `lambda arguments: expression`

The value of the expression is returned automatically — there's no `return` keyword.

### Lambda with one argument

#### Original Code

In [ ]:
x=lambda a: a+10
x(5)

15


#### What This Code Does

Creates a tiny function that adds 10 to its argument, stores it in `x`, then calls it with `5`.

#### Line-by-Line Breakdown

| Line | What happens |
|------|--------------|
| `x = lambda a: a+10` | `lambda a: a+10` is a function taking `a` and returning `a+10`. Assigned to `x`. |
| `x(5)` | Calls it: `5 + 10`. |

#### Why This Output Occurs

`a` becomes `5`; the expression `a + 10` evaluates to `15`, which is returned.

#### Common Mistakes

- Trying to put a statement (a `print` used for side effects, an assignment, or a loop) inside a lambda — only **one expression** is allowed.

---

### Lambda with multiple arguments

#### Original Code

In [ ]:
x=lambda a,b: a*b
x(5,6)

30


#### What This Code Does

A two-argument lambda that multiplies its inputs.

#### Line-by-Line Breakdown

| Line | What happens |
|------|--------------|
| `x = lambda a,b: a*b` | Function of `a` and `b` returning `a*b`. |
| `x(5,6)` | `5 * 6`. |

#### Why This Output Occurs

`a=5`, `b=6`, so `a*b = 30` is returned.

#### Common Mistakes

- Forgetting that arguments are positional: `x(6,5)` would still be `30` here, but for non-commutative operations (subtraction, division) order matters.

---

### Named function vs. lambda: even/odd

#### Original Code (named function)

In [ ]:
def is_even(x):
    if x%2==0:
        print(f'{x} is even')
    else:
        print(f'{x} is odd')
is_even(347)

347 is even is odd


#### What This Code Does

A regular `def` that **prints** whether a number is even or odd using a full `if/else` **statement**.

#### Line-by-Line Breakdown

| Line | What happens |
|------|--------------|
| `def is_even(x):` | Defines the function. |
| `if x%2==0:` | `x % 2` is the remainder when divided by 2; `0` means even. |
| `print(... even)` / `print(... odd)` | Side-effect output for each branch. |
| `is_even(347)` | `347 % 2 == 1`, so the `else` branch runs. |

Wait — let's be precise. `347 % 2` is `1` (not `0`), so the `else` branch runs and it prints:

```text
347 is odd
```

#### Why This Output Occurs

347 is odd, so `347 % 2 == 0` is `False`; the `else` branch prints `347 is odd`. The function **returns `None`** (it only prints).

#### Common Mistakes

- The name `is_even` suggests it returns a boolean, but it actually **prints** and returns `None`. Name functions for what they do.

---

#### Original Code (lambda equivalent)

In [ ]:
even=lambda x: f"{x} is even" if x%2==0 else f'{x} is odd'
even(347)

'347 is odd'


#### What This Code Does

Does the same even/odd check, but as a **single expression** that **returns** a string. It has to use a **ternary (conditional) expression**, because a lambda can't contain an `if/else` *statement*.

#### Line-by-Line Breakdown

| Line | What happens |
|------|--------------|
| `even = lambda x: <expr> if x%2==0 else <expr>` | The body is one expression: a **ternary**. |
| `f"{x} is even" if x%2==0 else f'{x} is odd'` | Reads as: *"this value if the condition, else that value."* |
| `even(347)` | `347 % 2 == 0` is `False`, so the `else` value is returned. |

#### Why This Output Occurs

The ternary picks the `else` branch (`f'{x} is odd'`) because 347 is odd, and the lambda **returns** that string (note the quotes — it's a returned value, not printed text).

#### Common Mistakes

- Confusing the **ternary expression** (`A if cond else B` — produces a value) with the **`if` statement** (controls flow, produces no value). Only the expression form is allowed in a lambda.
- Expecting `even(347)` to *print* — it *returns* a string. You'd need `print(even(347))` to display it without quotes.

!!! warning "When NOT to use a lambda (PEP 8)"
    **Don't assign a lambda to a name.** PEP 8 is explicit about this: if you need a named function, use `def`. Writing `even = lambda x: ...` gains nothing over `def even(x): ...` and *loses* a useful name in tracebacks (a `def`'s name shows up in errors; a lambda shows as `<lambda>`).

    Use `lambda` for **throwaway, inline** functions passed straight to `map`/`filter`/`sorted`/`reduce`, for example `sorted(data, key=lambda x: x['salary'])`.

    Avoid lambdas that are long, contain nested ternaries, or that you'll reuse — reach for `def` instead.

---

<a id="ch3-built-in-higher-order-functions"></a>

## Built-in Higher-Order Functions

These four built-ins take a function as an argument. They're the everyday tools of functional Python.

!!! tip "Laziness (link to Chapter 3)"
    `map` and `filter` return **lazy iterators**, not lists. They compute values *on demand* and can only be consumed once. Wrap them in `list()` (or loop over them) to materialize results. See [Chapter 2: Iterators & Generators](chapter_02_iterators_generators/index.md).

### `map` — transform every item

`map(function, iterable)` applies `function` to each element and yields the results.

#### Original Code

In [ ]:
num=[1,2,3,4]
square=map(lambda x:x*x,num)
print(list(square))

[1, 4, 9, 16]


#### What This Code Does

Squares every number in `num`.

#### Line-by-Line Breakdown

| Line | What happens |
|------|--------------|
| `num = [1,2,3,4]` | Source list. |
| `square = map(lambda x: x*x, num)` | Builds a **lazy** map object; nothing is computed yet. |
| `print(list(square))` | `list()` forces evaluation, producing the squares. |

#### Why This Output Occurs

`map` applies `x*x` to each: `1→1, 2→4, 3→9, 4→16`.

#### Common Mistakes

- `print(square)` prints something like `<map object at 0x...>`, not the values — you have to call `list()`.
- Consuming a map object twice: after one `list(square)` it's exhausted, so a second `list(square)` gives `[]`.

---

#### Original Code (map with a built-in method)

In [ ]:
names=['john','alice']
result=map(str.upper,names)
print(list(result))

['JOHN', 'ALICE']


#### What This Code Does

Uppercases each name by passing the **unbound method** `str.upper` directly to `map`.

#### Line-by-Line Breakdown

| Line | What happens |
|------|--------------|
| `result = map(str.upper, names)` | For each name `n`, calls `str.upper(n)` (the same as `n.upper()`). No lambda needed. |
| `print(list(result))` | Materializes the iterator. |

#### Why This Output Occurs

`str.upper('john')` gives `'JOHN'`, and `str.upper('alice')` gives `'ALICE'`.

#### Common Mistakes

- Prefer `str.upper` over `lambda s: s.upper()` — it's cleaner and a bit faster.
- Passing `str.upper()` (with parentheses) is an error — you want the function object, not a call.

---

### `filter` — keep matching items

`filter(function, iterable)` keeps only the items where `function(item)` is truthy.

#### Original Code

In [ ]:
num=[1,2,3,4,5]
even=filter(lambda X:X%2==0,num)
print(list(even))

[2, 4]


#### What This Code Does

Keeps only the even numbers.

#### Line-by-Line Breakdown

| Line | What happens |
|------|--------------|
| `num = [1,2,3,4,5]` | Source list. |
| `even = filter(lambda X: X%2==0, num)` | Lazy filter: keeps items where `X % 2 == 0` is `True`. |
| `print(list(even))` | Materializes the kept items. |

#### Why This Output Occurs

The predicate is `True` only for `2` and `4`; odd numbers are dropped.

#### Common Mistakes

- The predicate must **return a boolean-ish value**. A predicate that *prints* instead of returning would filter everything out (`None` is falsy).
- Like `map`, `filter` is lazy and single-use.

---

### `reduce` — fold to a single value

`reduce(function, iterable)` combines items pairwise, carrying an accumulator, until one value remains. It lives in `functools`.

#### Original Code

In [ ]:
from functools import reduce
num=[1,2,3,4]
sum=reduce(lambda a,b:a+b, num)/ len(num)
print(sum)

2.5


#### What This Code Does

Computes the **average** of `num`: it `reduce`s the list to a total, then divides by the count.

#### Line-by-Line Breakdown

| Line | What happens |
|------|--------------|
| `from functools import reduce` | `reduce` isn't a built-in, so import it. |
| `reduce(lambda a,b: a+b, num)` | Folds pairwise: `((1+2)+3)+4 = 10`. |
| `/ len(num)` | Divides the total `10` by `4`. |
| `sum = ...` | Stores the result in a variable named `sum`. (Watch out.) |
| `print(sum)` | Prints the average. |

#### Why This Output Occurs

**How `reduce` folds:**

```text
step 1: a=1, b=2  -> 3
step 2: a=3, b=3  -> 6
step 3: a=6, b=4  -> 10
total = 10
10 / 4 = 2.5
```

`reduce` carries the running result (`a`) and combines it with the next item (`b`), one pair at a time.

#### Common Mistakes — shadowing the built-in `sum`

- **`sum = ...` shadows the built-in `sum()` function.** After this line, in the same scope, `sum` is a `float` (`2.5`), not a function. If you later write `sum([1,2,3])` you'll get `TypeError: 'float' object is not callable`. This is the same family of bug as the `say_hello()` error at the start of the chapter — a name that *was* callable has been reassigned to a non-callable value.
- **Never name variables after built-ins** (`sum`, `list`, `dict`, `str`, `type`, `id`, `max`, `min`, `filter`, `map`, `input`). Use `total`, `result`, or `average` instead.
- This particular computation is clearer as `sum(num) / len(num)` using the built-in. `reduce` earns its keep for *custom* combinations (a running product, flattening, and so on) where no built-in exists.

---

### `sorted` — order by a custom key

`sorted(iterable, key=..., reverse=...)` returns a **new sorted list**. The `key` function maps each item to the value you want to sort by.

#### Original Code (sort dicts by salary, descending)

In [ ]:
employee =[
    {"name":"A","salary":5000},
    {"name":"B","salary":3000},
]
sorted_emp=sorted(employee, key=lambda x:x['salary'], reverse=True)
print(sorted_emp)

[{'name': 'A', 'salary': 5000}, {'name': 'B', 'salary': 3000}]


#### What This Code Does

Sorts a list of employee dictionaries by their `salary`, highest first.

#### Line-by-Line Breakdown

| Line | What happens |
|------|--------------|
| `employee = [...]` | A list of dicts. You can't sort dicts directly — there's no natural order. |
| `key=lambda x: x['salary']` | Tells `sorted` to compare each dict by its `salary` value. |
| `reverse=True` | Descending order (highest salary first). |
| `print(sorted_emp)` | Shows the new sorted list. |

#### Why This Output Occurs

A's salary (5000) is greater than B's (3000), and `reverse=True` puts the larger first, so A comes before B.

#### Common Mistakes

- Omitting `key` raises `TypeError`, because dicts aren't orderable.
- Confusing `sorted()` (returns a new list, works on any iterable) with `list.sort()` (sorts in place, returns `None`).

---

#### Original Code (sort by length)

In [ ]:
a=['ram','shyam']
res=sorted(a,key=len)
print(res)

['ram', 'shyam']


#### What This Code Does

Sorts strings by their **length** instead of alphabetically.

#### Line-by-Line Breakdown

| Line | What happens |
|------|--------------|
| `key=len` | The built-in `len` function becomes the sort key: each string is compared by its character count. |
| `res = sorted(a, key=len)` | `'ram'` (3) before `'shyam'` (5). |

#### Why This Output Occurs

`len('ram')` is `3`, `len('shyam')` is `5`. Ascending order puts the shorter string first.

#### Common Mistakes

- Writing `key=len()` — pass the function `len`, not a call.
- `key` accepts any callable: a built-in (`len`, `str.lower`), a lambda, or a named function.

---

### Summary table

| Function | What it does | Returns | Lazy? | Typical use |
|----------|--------------|---------|-------|-------------|
| `map(f, it)` | Apply `f` to every item | `map` object (iterator) | Yes | Transform each element |
| `filter(f, it)` | Keep items where `f(item)` is truthy | `filter` object (iterator) | Yes | Select a subset |
| `reduce(f, it)` | Fold pairwise into one value | A single value | No | Aggregate / accumulate |
| `sorted(it, key=...)` | Sort items by `key` | A new `list` | No | Order records by a field |

!!! tip "Comprehensions are often more Pythonic"
    For `map` and `filter`, a **list comprehension** is usually clearer and just as fast:

In [ ]:
squares = [x*x for x in num]            # vs map(lambda x: x*x, num)
evens   = [x for x in num if x%2==0]    # vs filter(lambda x: x%2==0, num)

    See [Chapter 1: Comprehensions](chapter_01_comprehensions/index.md). Reach for `map`/`filter` when you already have a named function to apply (for example `map(str.upper, names)`) or want laziness over a huge stream.

---

<a id="ch3-real-industry-usage"></a>

## Real Industry Usage

- **Data transformation pipelines (pandas):** `df['col'].apply(func)`, `df['col'].map(mapping)`, and `df.apply(...)` are higher-order functions you'll use constantly for cleaning and deriving columns.
- **Big data — Spark / MapReduce:** the whole MapReduce paradigm is `map` then `reduce` at cluster scale. Spark's `rdd.map(...)`, `.filter(...)`, and `.reduceByKey(...)` are the same ideas spread across machines.
- **Event and callback handlers:** GUI buttons, web frameworks, and async code take functions as callbacks (`button.on_click(handler)`, `app.route(...)`). You hand over a *verb* to be performed later.
- **Sorting records by custom keys:** `sorted(orders, key=lambda o: o.created_at)`, `max(employees, key=lambda e: e.salary)`, `min(...)` — `key=` shows up all over real data code.
- **Function dispatch tables / strategy pattern:** `handlers = {"email": send_email, "sms": send_sms}`, then `handlers[kind](msg)` replaces sprawling `if/elif` and makes adding behavior a one-line change.
- **AI agent tool routing:** as shown above, agents map a chosen tool name to a Python function and call it — a dispatch table of tools.
- **Key functions in `sorted`/`max`/`min`:** the `key=` argument is the most common place beginners meet higher-order functions in production.

---

<a id="ch3-quick-recap"></a>

## Quick Recap

- Functions are **first-class objects** — you can store, pass, and return them.
- **Referencing** (`greet`) is not the same as **calling** (`greet('ram')`). Calling a no-`return` function gives `None`, and calling `None` raises `TypeError: 'NoneType' object is not callable`.
- A **higher-order function** takes and/or returns functions. `execute(func, value)` is the template.
- Replace `if/elif` dispatch with **passing functions** or a **dict dispatch table** — the AI-agent tool pattern.
- A **`lambda`** is a one-expression anonymous function; use **ternary expressions** inside it, never statements. Don't *name* a lambda (use `def`).
- **`map`** transforms, **`filter`** selects (both lazy iterators), **`reduce`** folds to one value, **`sorted`** orders by `key`.
- Don't shadow built-ins (`sum`, `list`, and friends). List comprehensions are often the more Pythonic alternative to `map`/`filter`.

---

<a id="ch3-interview-questions"></a>

## Interview Questions

### Beginner

??? note "1. What is a higher-order function? Give an example."
    A function that takes another function as an argument and/or returns a function. Example: `sorted(data, key=len)` takes `len` (a function) as the `key`. Or a custom `execute(func, value): return func(value)`.

??? note "2. What's the difference between `greet` and `greet('ram')`?"
    `greet` is the **function object** (the recipe). `greet('ram')` **calls** it and evaluates to its return value (the cooked meal). If `greet` has no `return`, `greet('ram')` is `None`. Use `greet` (no parentheses) to pass or store it for later.

??? note "3. What is a `lambda` and what is its main limitation?"
    A small anonymous function written as `lambda args: expression`. Its limitation: the body is a **single expression** — no statements (`if`/`for`/assignments), so multi-step logic needs a real `def`. The expression's value is returned automatically.

### Intermediate

??? note "1. `lambda` vs `def` — when do you use each?"
    Use `lambda` for short, throwaway, inline functions passed to `map`/`filter`/`sorted`/`reduce`. Use `def` for anything named, reusable, multi-line, or that benefits from a docstring and a readable name in tracebacks. PEP 8 says don't assign a lambda to a variable — use `def` instead.

??? note "2. Why do `map` and `filter` return iterators instead of lists?"
    For **laziness and memory efficiency**: they compute values on demand, so you can chain them over huge or infinite streams without building intermediate lists. The trade-off is they're single-use and have to be wrapped in `list()` (or iterated) to see results.

??? note "3. What does the `key=` argument do in `sorted`/`max`/`min`?"
    It's a function applied to each element to produce the value used for comparison. `sorted(words, key=len)` sorts by length; `max(emps, key=lambda e: e.salary)` finds the highest-paid. It lets you sort or compare by a derived field without changing the items themselves.

### Advanced

??? note "1. `reduce` vs `sum` — when is each appropriate?"
    `sum(iterable)` is a fast, readable built-in for adding numbers — prefer it for sums. `reduce(func, iterable)` is the general fold for **custom** combinations (running product, flattening lists, building a max-by, combining dicts) where no built-in exists. Overusing `reduce` for simple sums hurts readability; the average example `reduce(lambda a,b:a+b, num)/len(num)` is clearer as `sum(num)/len(num)`.

??? note "2. List comprehension vs `map`/`filter` — which is more Pythonic?"
    Comprehensions (`[f(x) for x in it if cond]`) are generally preferred for readability and because they avoid lambdas. `map`/`filter` are a good fit when applying an **existing named function** (`map(str.upper, names)`) or when you want laziness over a large stream (or use a generator expression for a lazy comprehension). Both are valid; pick the clearer one.

??? note "3. Explain the bug in `sum = reduce(lambda a,b:a+b, num)/len(num)`."
    It computes correctly (`2.5`), but assigns the result to a variable named `sum`, which **shadows the built-in `sum`** in that scope. Afterward, `sum([1,2,3])` raises `TypeError: 'float' object is not callable` because `sum` is now `2.5`, not a function. Fix: rename to `average` or `total`. This is the same "name that was callable is now a value" trap as calling `None`.

---

<a id="ch3-practice-exercises"></a>

## Practice Exercises

**Easy**

1. Write a lambda `triple = lambda n: n * 3` and call it on `7`. Then rewrite it as a `def` and explain which PEP 8 prefers.
2. Given `nums = [5, 12, 17, 22, 30]`, use `map` to produce a list of each number squared, and `filter` to keep only those divisible by 3. Then rewrite both with comprehensions.

**Medium**

1. Given `words = ['banana', 'kiwi', 'apple', 'fig']`, sort them (a) alphabetically, (b) by length, and (c) by length descending. Use `sorted` with `key=` for each.
2. You have `people = [{'name':'A','age':30}, {'name':'B','age':25}, {'name':'C','age':40}]`. Use `sorted` to order by age ascending, and `max`/`min` with `key=` to find the oldest and youngest person.
3. Build a **dispatch table** `ops = {'add': lambda a,b: a+b, 'mul': lambda a,b: a*b, 'sub': lambda a,b: a-b}` and write `calc(op, a, b)` that looks up and runs the right operation. Replace any `if/elif`.

**Hard**

1. Using `reduce`, compute the **product** of `[1,2,3,4,5]` (should be 120) and, separately, **flatten** `[[1,2],[3,4],[5]]` into `[1,2,3,4,5]`. Explain why `sum` can't do the product.
2. Without using the built-in `max`, write `my_max(items, key=...)` using `reduce` that returns the item with the largest key value. Test it on the `people` list above to find the oldest.

---

<a id="ch3-challenge-project"></a>

## Challenge Project

### Mini Sales Data Pipeline (parse → map → filter → reduce)

Build a small data-processing pipeline over a list of sales records using only higher-order functions, `lambda`, `map`, `filter`, `reduce`, and `sorted`.

**Input data:**

In [ ]:
sales = [
    {"product": "pen",    "qty": 10, "price": 1.5},
    {"product": "laptop", "qty": 2,  "price": 800.0},
    {"product": "pencil", "qty": 50, "price": 0.5},
    {"product": "monitor","qty": 3,  "price": 150.0},
    {"product": "eraser", "qty": 25, "price": 0.2},
]

**Spec — produce:**

1. **map (transform):** a new list where each record gains a `"total"` key = `qty * price`.
2. **filter (select):** keep only records whose `total` is **≥ 50**.
3. **reduce (aggregate):** the **grand total revenue** of the filtered records.
4. **sorted (order):** the filtered records sorted by `total`, highest first.
5. Print a small report: each surviving product with its total, then the grand total.

**Hints:**

- For step 1, `map` a lambda that returns a new dict: `lambda r: {**r, "total": r["qty"]*r["price"]}`.
- For step 2, `filter(lambda r: r["total"] >= 50, ...)` — remember to `list()` if you'll reuse it.
- For step 3, `reduce(lambda acc, r: acc + r["total"], filtered, 0)` (note the `0` initial value — handy when the list might be empty).
- For step 4, `sorted(filtered, key=lambda r: r["total"], reverse=True)`.
- Don't name your accumulator `sum`. Use `total_revenue`.

**Stretch goals:**

- Replace the `map`/`filter` steps with comprehensions and compare readability.
- Build a **dispatch table** of report formatters (`{"short": ..., "verbose": ...}`) chosen by a `style` argument — the strategy pattern with lambdas.

### Alternative: Dict-of-lambdas Calculator

Build a calculator that dispatches operations from a dictionary of lambdas:

In [ ]:
ops = {
    "+": lambda a, b: a + b,
    "-": lambda a, b: a - b,
    "*": lambda a, b: a * b,
    "/": lambda a, b: a / b if b != 0 else "error: divide by zero",
}

**Spec:** write `calc(a, op, b)` that looks up `ops[op]` and calls it. Handle an unknown operator gracefully (for example, return a helpful message instead of `KeyError`). This is the **strategy pattern / dispatch table** in miniature — exactly how the AI tool-routing example earlier works.

---

Previous: [Chapter 2 — Iterators & Generators](chapter_02_iterators_generators/index.md)

Next up: [Chapter 4 — Decorators & Properties](chapter_04_decorators_properties/index.md)

---

<a id="ch4"></a>

# Chapter 4: Decorators & Properties

> **The big idea:** *original function → decorator adds something → enhanced function.*
> A **decorator** wraps a function to add extra behavior without modifying the original function's code. A **property** does the same trick for attributes — letting `person.name` quietly run validation or computation behind the scenes.

---

<a id="ch4-learning-objectives"></a>

## Learning Objectives

By the end of this chapter you will be able to:

- Explain what a decorator is and why it exists (the "wrap, don't rewrite" idea).
- Read and write your own decorator using nested functions and closures.
- Understand `@decorator` as syntactic sugar for `func = decorator(func)`.
- Build a validation/auth decorator that protects many functions at once (DRY).
- Turn a fragile decorator into a production-grade one using `*args, **kwargs` and `functools.wraps`.
- Use the built-in `@property` to create managed attributes with getter / setter / deleter.
- Diagnose the classic `AttributeError` that appears after a deleter removes the backing attribute.
- Recognize real-world decorators you've already met (`@app.route`, `@lru_cache`, `@login_required`, `@staticmethod`, `@classmethod`, `@pytest.fixture`).

---

<a id="ch4-concept-explanation"></a>

## Concept Explanation

### What is a decorator?

A decorator is a function that takes another function and returns a new function that usually does something extra — before, after, or around the original.

> **Intuition:** A decorator is a wrapper. The thing inside the wrapper is unchanged; the wrapper just adds stuff around it.

**Beginner view —** "It adds features to a function for me."
You have a function `intro()`. You want a polite greeting before it and a sign-off after it — but you don't want to edit `intro()`. A decorator adds those for you.

**Intermediate view —** "It's a function transformer."
`decorator(func)` returns a new function (the `wrapper`). The name `intro` now points at the wrapper, and the wrapper calls the original `func` somewhere inside itself.

**Advanced view —** "It's an application of closures plus first-class functions."
Because functions in Python are first-class objects (you can pass them around, store them, return them) and Python supports nested functions that remember their enclosing scope (closures), a decorator can capture the original `func` in a closure and return a brand-new callable. The `@` symbol is just sugar for rebinding the name.

**Real-world intuition —** decorators handle cross-cutting concerns: things many functions need but that aren't the function's core job — logging, timing, authentication, caching, retrying, input validation. Instead of copy-pasting that logic into 50 functions, you write it once as a decorator.

### Visual analogies

| Analogy | Original | Decorator | Result |
|---|---|---|---|
| Gift-wrapping | the present | the wrapping paper + bow | a wrapped gift (still the same present inside) |
| Coffee add-ons | espresso shot | milk + sugar + foam | a latte (espresso is untouched) |
| Sandwich | the filling | the bread on both sides | a sandwich |
| Airport security | your flight | check-in before + baggage claim after | your whole journey, "wrapped" |

In every case the core is unchanged — the wrapper just surrounds it with extra steps.

### Prerequisites (don't skip these)

Decorators are built on two ideas from functional programming:

1. **Functions are first-class** — they can be passed as arguments and returned from other functions.
2. **Nested functions and closures** — an inner function can remember variables from the outer function that created it.

If either feels shaky, review **[Chapter 3 — Functional Programming](chapter_03_functional_programming/index.md)** first. A decorator is literally "a function that returns a nested function (closure)."

### The flow

```mermaid
flowchart LR
    A["original function<br/>intro()"] --> B["decorator wraps it<br/>@conversation"]
    B --> C["enhanced function<br/>greet + intro + sign-off"]
```

```mermaid
sequenceDiagram
    participant Caller
    participant Wrapper as wrapper()
    participant Original as func() (original)
    Caller->>Wrapper: call enhanced function
    Wrapper->>Wrapper: run code BEFORE ("hello sir")
    Wrapper->>Original: func()
    Original-->>Wrapper: original behavior runs
    Wrapper->>Wrapper: run code AFTER ("Nice to meet you")
    Wrapper-->>Caller: done
```

---

<a id="ch4-writing-your-first-decorator"></a>

## Writing Your First Decorator

### Step 1 — A plain function (no decorator yet)

Before we add any decorator, let's see the manual way of surrounding a function with extra steps.

#### Original Code

In [ ]:
def intro():
    print("my name is bla bla bla")

print("hello sir")
intro()
print("and what about you")

hello sir
my name is bla bla bla
and what about you


#### What This Code Does

Defines a simple function `intro()` that prints one line, then manually prints a greeting before calling it and another line after.

#### Line-by-Line Breakdown

- `def intro():` — defines a function with no parameters.
- `print("my name is bla bla bla")` — the function's only job.
- `print("hello sir")` — runs first, outside the function.
- `intro()` — calls the function (prints its line).
- `print("and what about you")` — runs last, outside the function.

#### Why This Output Occurs

Statements run top to bottom. The greeting prints, then `intro()` executes its body, then the closing line prints. The before/after behavior is hard-coded by hand here, and that doesn't scale: if you had 10 intro functions you'd repeat those two `print`s ten times. That repetition is exactly what a decorator removes.

#### Common Mistakes

- Writing `intro` instead of `intro()` — `intro` is the function object, `intro()` actually calls it. Forgetting the parentheses is the number one beginner decorator bug too.

---

### Step 2 — The decorator pattern

Now we extract that "greeting before / sign-off after" wrapper into a reusable decorator.

#### Original Code

In [ ]:
def conversation(func):
    def wrapper():
        print("hello sir")
        func()
        print("Nice to meet you")
        print("-"*50)
    return wrapper

@conversation
def intro_ram():
    print("my name is ram")

@conversation
def intro_shyam():
    print("my name is shyam")

intro_ram()
intro_shyam()

#### What This Code Does

Defines a decorator `conversation` that wraps any no-argument function with a greeting before it and a sign-off (plus a divider line) after it. It then decorates two functions and calls them.

#### Line-by-Line Breakdown

- `def conversation(func):` — the decorator. It receives the function to be decorated as `func`.
- `def wrapper():` — a nested function. This is the enhanced function that will actually run.
- `print("hello sir")` — extra behavior before the original.
- `func()` — calls the original function. This is the heart of every decorator.
- `print("Nice to meet you")` and `print("-"*50)` — extra behavior after (`"-"*50` repeats `-` fifty times).
- `return wrapper` — the decorator returns the new function. It returns the function object, it does not call it (no parentheses).
- `@conversation` above `intro_ram` — this is syntactic sugar for:

In [ ]:
intro_ram = conversation(intro_ram)

hello sir
my name is ram
Nice to meet you
--------------------------------------------------
hello sir
my name is shyam
Nice to meet you
--------------------------------------------------


  After this line, the name `intro_ram` no longer points at the original — it points at `wrapper`.
- `intro_ram()` / `intro_shyam()` — these now call `wrapper`, which runs the before-code, the original, then the after-code.

#### Why This Output Occurs

When you call `intro_ram()`, you're really calling `wrapper()`. The wrapper prints `"hello sir"`, then `func()` runs the original `intro_ram` body (`my name is ram`), then prints the sign-off and divider. The same wrapper logic is reused for `intro_shyam` — that's the whole point: write the surrounding behavior once, apply it many times.

> **Key insight:** `@conversation` is exactly `intro_ram = conversation(intro_ram)`. The `@` is just a cleaner way to write that reassignment, placed right where the function is defined.

#### Common Mistakes

- **`return wrapper()` instead of `return wrapper`.** Adding `()` calls the wrapper immediately and returns its (usually `None`) result, so your decorated name becomes `None` and `intro_ram()` crashes with `TypeError: 'NoneType' object is not callable`.
- **Forgetting `return wrapper` entirely** — then `conversation(func)` returns `None`, same crash.
- **Wrapper signature mismatch** — `wrapper()` takes no arguments, so this version only works on functions that take no arguments. We fix that next.

---

<a id="ch4-real-world-decorator-validation-auth"></a>

## Real-World Decorator: Validation / Auth

Greetings are cute, but decorators earn their keep with cross-cutting concerns like authentication and input validation.

### Step 1 — The manual version (no decorator)

#### Original Code

In [ ]:
def user_login(email):
    if email.endswith("@gmail.com"):
        print("acessing db...")
        print("checking username and password")
        print("logged in....")
    else:
        print("only gmail user are allowed")

user_login("abc@gmail.com")

acessing db...
checking username and password
logged in....


#### What This Code Does

A login function that first checks the email is a Gmail address, and only then performs the login steps.

#### Line-by-Line Breakdown

- `def user_login(email):` — takes an `email` argument.
- `if email.endswith("@gmail.com"):` — validation guard.
- The three `print`s inside the `if` simulate the real work (DB access, credential check, success).
- `else:` — rejects non-Gmail addresses.
- `user_login("abc@gmail.com")` — passes the check, so the login steps run.

#### Why This Output Occurs

`"abc@gmail.com".endswith("@gmail.com")` is `True`, so the `if` branch runs all three lines and the `else` is skipped.

#### Common Mistakes

- **The validation is glued to this one function.** If `update_profile`, `delete_account`, and friends also need the same Gmail check, you'd copy-paste the `if/else` everywhere — a maintenance headache. The moment the rule changes, you have to edit every copy.

---

### Step 2 — Extract the validation into a decorator

Same rule, written once, applied to many functions.

#### Original Code

In [ ]:
def validate_email(func):
    def wrapper(email):
        print("validating email...")
        if email.endswith("@gmail.com"):
            func(email)
        else:
            print("please provide valid email address")
    return wrapper

@validate_email
def user_login(email):
    print("accessing db")
    print("logged in successfully")

@validate_email
def update_profile(email):
    print("updating email and username")
    print("please login once again")

user_login("abc@gmail.com")
update_profile("bcd@gmail.com")

validating email...
accessing db
logged in successfully
validating email...
updating email and username
please login once again


#### What This Code Does

Defines `validate_email`, a decorator that checks the email before allowing the wrapped function to run. Two unrelated functions (`user_login`, `update_profile`) are both protected by the same single decorator.

#### Line-by-Line Breakdown

- `def validate_email(func):` — the decorator; `func` is the function being protected.
- `def wrapper(email):` — note the wrapper accepts `email`, because the functions it wraps take an `email` argument. The wrapper's signature has to match what callers pass.
- `print("validating email...")` — runs before every protected function.
- `if email.endswith("@gmail.com"): func(email)` — only if valid do we call the original function, forwarding the `email` argument.
- `else: print("please provide valid email address")` — rejection path; the original never runs.
- `return wrapper` — hand back the enhanced function.
- `@validate_email` on both functions — each becomes `func = validate_email(func)`.
- The two calls pass valid Gmail addresses, so both proceed.

#### Why This Output Occurs

Each call routes through `wrapper`: it prints `"validating email..."`, the address ends with `@gmail.com` so it calls the real function and forwards `email`. The validation logic lives in one place but guards both functions — this is DRY (Don't Repeat Yourself) and a textbook cross-cutting concern.

> **Why this is better:** One decorator now protects many functions. Change the rule once (say, allow `@company.com` too) and every decorated function updates automatically.

#### Common Mistakes

- **Wrapper signature mismatch (the big one).** If you write `def wrapper():` here, calling `user_login("abc@gmail.com")` crashes with `TypeError: wrapper() takes 0 positional arguments but 1 was given`. The wrapper has to accept the same arguments the caller sends, and forward them to `func`.
- **Forgetting to forward the argument** — writing `func()` instead of `func(email)` drops the data the original needs.
- **Forgetting `return func(...)`** — if the original returns a value, the wrapper has to `return func(email)` or the result is silently lost (becomes `None`).

---

!!! tip "Production-grade pattern: `*args, **kwargs` + `functools.wraps`"

    The wrappers above only work for specific signatures. A solid decorator should accept any arguments and return the original's result. It should also use `functools.wraps` so the wrapped function keeps its real name, docstring, and metadata — which matters for debugging, `help()`, and frameworks.

In [ ]:
import functools

def validate_email(func):
    @functools.wraps(func)            # preserves func's name/docstring/metadata
    def wrapper(*args, **kwargs):     # accepts ANY arguments
        email = kwargs.get("email", args[0] if args else None)
        print("validating email...")
        if email and email.endswith("@gmail.com"):
            return func(*args, **kwargs)   # forward everything AND return result
        print("please provide valid email address")
        return None
    return wrapper

    - `*args, **kwargs` — captures positional and keyword arguments of any shape.
    - `return func(*args, **kwargs)` — forwards them all and passes the return value back.
    - `@functools.wraps(func)` — without it, `user_login.__name__` would wrongly be `"wrapper"`. With it, introspection and tooling still see the real function.

    **Rule of thumb:** real-world decorators almost always look like `*args, **kwargs` plus `functools.wraps`.

### Decorators you already use

You've probably seen these decorators around — now you know how they work under the hood:

| Decorator | What it does |
|---|---|
| `@staticmethod`, `@classmethod` | Method types in classes — see **[Chapter 5 — OOP](chapter_05_oop/index.md)** |
| `@app.route("/")` (Flask) / `@app.get("/")` (FastAPI) | Registers a URL → function mapping |
| `@lru_cache` (`functools`) | Caches results so repeat calls are instant |
| `@pytest.fixture` | Provides reusable test setup/teardown |
| `@login_required` (Django/Flask) | Blocks access unless the user is authenticated |
| `@property` | Turns a method into a managed attribute (next section) |

---

<a id="ch4-the-property-decorator"></a>

## The @property Decorator

So far decorators wrapped functions. The built-in `@property` is a special decorator that wraps methods so you can access them like attributes — while still running code behind the scenes.

> **Why it matters:** It lets you expose a clean attribute interface (`person.name`) while quietly running validation, logging, or computation. It's the Pythonic replacement for Java-style `get_name()` / `set_name()` methods.

`@property` gives you three hooks:

- **getter** — runs on `person.name` (reading)
- **setter** — runs on `person.name = "..."` (writing)
- **deleter** — runs on `del person.name` (deleting)

### Step 1 — Reading via the getter

#### Original Code

In [ ]:
class Person:
    def __init__(self, name):
        self._name = name

    @property
    def name(self):
        print("Getting name...")
        return self._name

    @name.setter
    def name(self, value):
        print("Setting name...")
        self._name = value

    @name.deleter
    def name(self):
        print("Deleting name...")
        del self._name

person = Person("ram")
print(person.name)

Getting name...
ram


#### What This Code Does

Defines a `Person` class where `name` looks like a normal attribute but is actually managed by getter/setter/deleter methods. Then it creates a person and reads `.name`.

#### Line-by-Line Breakdown

- `self._name = name` — the backing attribute. The leading underscore is a convention meaning "internal; don't touch directly."
- `@property` above `def name(self):` — marks this method as the getter. Now `person.name` calls it.
- `return self._name` — the getter returns the stored value (after printing a trace line).
- `@name.setter` above `def name(self, value):` — the setter, used when you assign `person.name = ...`.
- `@name.deleter` above `def name(self):` — the deleter, used for `del person.name`.
- `print(person.name)` — accessing `.name` (no parentheses) triggers the getter.

#### Why This Output Occurs

`person.name` doesn't just fetch a value — it calls the getter method, which prints `"Getting name..."` and returns `self._name` (`"ram"`). `print(...)` then displays `ram`. Notice you write `person.name`, not `person.name()` — that's the whole point of `@property`: it looks like an attribute.

#### Common Mistakes

- Writing `person.name()` — this would try to call the returned string and crash with `TypeError: 'str' object is not callable`.
- Naming the backing field `self.name` instead of `self._name` — that causes infinite recursion, because `self.name = ...` re-triggers the setter, which sets `self.name` again, forever.

---

### Step 2 — Writing via the setter

#### Original Code

In [ ]:
person.name = "shyam"
print(person.name)

Setting name...
Getting name...
shyam


#### What This Code Does

Assigns a new value to `.name` (triggering the setter), then reads it back (triggering the getter).

#### Line-by-Line Breakdown

- `person.name = "shyam"` — assignment triggers the setter with `value="shyam"`, which prints `"Setting name..."` and stores `self._name = "shyam"`.
- `print(person.name)` — triggers the getter, printing `"Getting name..."` then returning the new value.

#### Why This Output Occurs

Two property hooks fire in sequence: first the setter (from the assignment), then the getter (from the read). This is what `@property` buys you — you can run validation or logging on both read and write while the user just sees `person.name`.

#### Common Mistakes

- Expecting assignment to be "silent." With a setter, every assignment runs your code — handy for validation, but be aware it has side effects.
- Putting heavy or slow logic in a getter or setter — since they run on every access, keep them cheap.

---

### Step 3 — Deleting via the deleter

#### Original Code

In [ ]:
del person.name

Deleting name...


#### What This Code Does

Deletes the managed attribute, triggering the deleter, which removes the backing field `_name`.

#### Line-by-Line Breakdown

- `del person.name` — triggers the deleter method.
- `print("Deleting name...")` — the trace line.
- `del self._name` — actually removes the backing attribute from the instance.

#### Why This Output Occurs

`del person.name` routes to the deleter, which prints its message and then `del self._name` removes the underlying storage. After this line, the object no longer has a `_name` attribute at all — remember this, it causes the next error.

#### Common Mistakes

- Assuming the object is unchanged after deletion. The backing data is gone — any later read will fail (see Step 4).

---

### Step 4 — The AttributeError (the key teaching moment)

#### Original Code

In [ ]:
person.name

Getting name...
AttributeError: 'Person' object has no attribute '_name'


#### What This Code Does

Tries to read `.name` again — but the deleter already removed the backing `_name`.

#### Line-by-Line Breakdown

- `person.name` — triggers the getter, which runs `return self._name`.
- But `self._name` was deleted in Step 3, so there's nothing to return.

#### Why This Output Occurs

This is the crux of how properties work. The getter still exists and still runs (you see `"Getting name..."` print first), but it executes `return self._name` — and `_name` no longer exists on the object because the deleter removed it. Python then raises `AttributeError`.

> **Teaching focus:** Two lessons in one error.
> 1. **Properties run code on attribute access** — that's why you see `"Getting name..."` even though the access ultimately fails.
> 2. **Accessing a deleted backing attribute errors.** The property (`name`) and its backing field (`_name`) are different things. Deleting the backing field breaks the getter.

#### Common Mistakes

- **Confusing `name` with `_name`.** The deleter removed `_name` (the storage), not the `name` property descriptor (which is defined on the class and still exists). The getter is fine; its data is missing.
- **No graceful fallback.** A safer getter might guard with `return getattr(self, "_name", None)` or re-raise a clearer message, so a deleted value doesn't crash callers unexpectedly.

---

### From manual getters/setters to `@property`

Back in **[Chapter 5 — OOP](chapter_05_oop/index.md)** you wrote explicit `get_salary()` / `set_salary()` methods (Java-style):

In [ ]:
# OOP-chapter style — explicit methods
class Employee:
    def get_salary(self):
        return self._salary
    def set_salary(self, value):
        if value < 0:
            raise ValueError("salary cannot be negative")
        self._salary = value

emp.set_salary(5000)     # clunky
print(emp.get_salary())  # clunky

`@property` modernizes this so callers use clean attribute syntax while you still get validation:

In [ ]:
# This-chapter style — Pythonic @property
class Employee:
    @property
    def salary(self):
        return self._salary

    @salary.setter
    def salary(self, value):
        if value < 0:
            raise ValueError("salary cannot be negative")
        self._salary = value

emp.salary = 5000     # clean, and STILL validated
print(emp.salary)     # clean

> **Best of both worlds:** a simple attribute interface on the outside, full control (validation/computation) on the inside. This is the idiomatic Python way.

---

<a id="ch4-real-industry-usage"></a>

## Real Industry Usage

| Area | How decorators / properties are used |
|---|---|
| **Web routing** | `@app.route("/users")` (Flask) and `@app.get("/users")` (FastAPI) register functions as HTTP endpoints. |
| **Auth & permissions** | `@login_required`, `@requires_role("admin")` gate access before the view runs. |
| **Logging / timing** | A `@timer` or `@log_calls` decorator measures or records every call without touching the function body. |
| **Retry / resilience** | A `@retry(times=3)` decorator re-runs a flaky network call on failure. |
| **Caching** | `@lru_cache` / `@functools.cache` memoize expensive pure functions for big speedups. |
| **Input validation** | One decorator validates payloads/arguments across many handlers (like `validate_email`). |
| **Plugin / handler registration** | Frameworks use decorators to register event handlers, CLI commands, or plugins into a registry. |
| **Computed `@property` fields** | `full_name` from `first + last`; `area` from `width * height`; temperature `celsius`↔`fahrenheit` conversion. |
| **Validated model fields** | ORM models (Django, SQLAlchemy) and Pydantic use property-like descriptors to validate/transform fields (e.g. reject a negative `balance`). |

---

<a id="ch4-quick-recap"></a>

## Quick Recap

- A **decorator** wraps a function to add behavior without editing it: *original → wrap → enhanced.*
- `@decorator` is sugar for `func = decorator(func)`.
- A decorator is built from a nested `wrapper` function (closure) and `return wrapper` (no parentheses).
- The wrapper's signature has to match what callers pass; production decorators use `*args, **kwargs` and `return func(*args, **kwargs)`.
- Use `functools.wraps` to preserve the wrapped function's name/docstring/metadata.
- Decorators shine for cross-cutting concerns: auth, validation, logging, timing, retry, caching.
- `@property` turns a method into a managed attribute with getter / setter / deleter.
- Reading a deleted backing attribute raises `AttributeError` — the getter runs, but its data is gone.
- `@property` is the Pythonic replacement for `get_x()` / `set_x()`.

---

<a id="ch4-interview-questions"></a>

## Interview Questions

### Beginner

??? note "Show answer — What is a decorator in Python?"
    A decorator is a function that takes another function as input and returns a new function that adds behavior before/after (or around) the original — without modifying the original's code. It's applied with the `@decorator` syntax above a function definition.

??? note "Show answer — What does the `@` symbol actually do?"
    `@decorator` placed above `def func` is syntactic sugar for `func = decorator(func)`. It rebinds the name `func` to whatever the decorator returns (usually the inner `wrapper`).

??? note "Show answer — What is the difference between `@property` and a normal attribute?"
    A normal attribute just stores/returns a value. A `@property` looks like an attribute from the outside (`obj.x`) but actually runs a method (getter) when read — and optionally a setter on assignment and a deleter on `del`. This lets you run validation/computation while keeping clean attribute syntax.

### Intermediate

??? note "Show answer — Why use `functools.wraps`?"
    Without it, the wrapper replaces the original function's identity: `func.__name__` becomes `"wrapper"`, the docstring is lost, and tools/frameworks that introspect functions misbehave. `@functools.wraps(func)` copies the original's `__name__`, `__doc__`, and other metadata onto the wrapper.

??? note "Show answer — How do you pass arguments through a decorator?"
    Make the wrapper accept `*args, **kwargs` and forward them: `def wrapper(*args, **kwargs): return func(*args, **kwargs)`. This works for any signature and also passes the return value back. Forgetting to forward args (or to `return`) is a common bug.

??? note "Show answer — Can decorators be stacked?"
    Yes. Multiple decorators apply bottom-up: 

In [ ]:
@a
@b
def f(): ...

    is equivalent to `f = a(b(f))`. `b` wraps `f` first, then `a` wraps the result. Order matters (e.g. `@auth` then `@log` behaves differently from the reverse).

### Advanced

??? note "Show answer — How do you write a decorator that takes arguments (a decorator factory)?"
    Add an extra outer layer that takes the arguments and returns the actual decorator:

In [ ]:
import functools
def retry(times):
    def decorator(func):
        @functools.wraps(func)
        def wrapper(*args, **kwargs):
            for _ in range(times):
                try:
                    return func(*args, **kwargs)
                except Exception:
                    continue
            raise
        return wrapper
    return decorator

@retry(times=3)
def fetch(): ...

    `@retry(times=3)` first calls `retry(3)`, which returns `decorator`, which then wraps `fetch`.

??? note "Show answer — Why does accessing a property after its deleter ran raise `AttributeError`?"
    The deleter typically removes the backing attribute (e.g. `del self._name`). The property descriptor itself still exists on the class, so the getter still runs — but its body does `return self._name`, and `_name` no longer exists on the instance, so Python raises `AttributeError: 'Person' object has no attribute '_name'`. The property and its backing field are separate things.

??? note "Show answer — When would you NOT use a decorator?"
    When the added behavior is unique to one function (no reuse benefit), when it would obscure control flow, when you need fine-grained per-call control that's clearer inline, or when the overhead of an extra function call matters in a hot loop. Decorators pay off for repeated, cross-cutting concerns.

---

<a id="ch4-practice-exercises"></a>

## Practice Exercises

### **Easy**

1. **Greeting decorator** — Write a decorator `@shout` that uppercases and prints `"!!!"` after whatever the wrapped function prints. Apply it to a `say_hi()` function.
2. **Banner decorator** — Write `@banner` that prints a line of `=` (length 40) before and after the wrapped function's output. Use `*args, **kwargs` so it works on any function.

### **Medium**

1. **`@timer`** — Write a decorator that measures and prints how long the wrapped function took to run (use `time.perf_counter()`), forwards `*args, **kwargs`, and returns the original's result. Use `functools.wraps`.

2. **`Temperature` with `@property`** — Build a class storing `_celsius`. Expose `celsius` as a property with a setter that rejects values below -273.15 (`ValueError`). Add a computed `fahrenheit` property (`c * 9/5 + 32`) with no setter.

### **Hard**

1. **`@retry`** — Write a decorator factory `@retry(times=3, delay=1)` that re-runs the function on exception up to `times`, sleeping `delay` seconds between attempts, and re-raises if all attempts fail. Preserve metadata with `functools.wraps`.
2. **`@log_calls` with stacking** — Write a `@log_calls` decorator that logs the function name and arguments before each call. Stack it with your `@timer` and verify the order of output, then swap the order and explain the difference.

---

<a id="ch4-challenge-project"></a>

## Challenge Project

### Mini Access-Control System + Validated `BankAccount`

Build a small system that combines decorators for authorization with a validated `@property`.

**Spec:**

1. **`@requires_role(role)`** — a decorator factory. It wraps a function and only runs it if the current user has the required role; otherwise it prints/raises `"Permission denied"`. Assume each protected function receives a `user` dict like `{"name": "ram", "role": "admin"}` as its first argument.

2. **`BankAccount` class:**
   - Store the balance in `_balance`.
   - Expose `balance` as a `@property` (getter).
   - Add a `balance` **setter** that rejects negative values with `ValueError("balance cannot be negative")`.
   - Methods `deposit(amount)` and `withdraw(amount)` that update `balance` through the property (so validation always applies). `withdraw` must reject amounts greater than the current balance.

3. **Wire it together:** a `transfer(user, src, dst, amount)` function decorated with `@requires_role("admin")` that moves money between two `BankAccount`s. Test it with both an admin user (succeeds) and a regular user (denied).

**Hints:**
- The decorator factory has three layers: `def requires_role(role): def decorator(func): def wrapper(user, *args, **kwargs): ... return wrapper; return decorator`.
- In `wrapper`, check `if user.get("role") != role:` before calling `func`.
- In `withdraw`, set `self.balance = self.balance - amount` so the setter's validation fires automatically.
- Use `@functools.wraps(func)` on the wrapper.

**Stretch goals:**
- Add an `@audit_log` decorator that records every transfer, and stack it with `@requires_role`.
- Add a computed `is_overdrawn` property.
- Build a tiny route registry: a `routes = {}` dict and a `@route("/path")` decorator that registers handler functions into it — a mini Flask.



<a id="ch5"></a>

# Chapter 5: Object-Oriented Programming (OOP)

> From loose functions to real-world entities — learning to model the world in code.

---

<a id="ch5-learning-objectives"></a>

## Learning Objectives

By the end of this chapter you will be able to:

- Explain **why** OOP exists and when it beats procedural code.
- Define **classes** and create **objects** (instances) from them.
- Distinguish **class attributes** vs **instance attributes**.
- Use the three method types: **instance**, **class** (`@classmethod`), and **static** (`@staticmethod`).
- Apply the **four pillars**: Inheritance, Polymorphism, Encapsulation, Abstraction.
- Read and write all five **inheritance** types and understand `super()` and the **MRO**.
- Understand why Python has **no true method overloading** and how to fake it.
- Use **access modifiers** (`public`, `_protected`, `__private`) and **name mangling**.
- Build **abstract base classes** with `abc.ABC` and `@abstractmethod`.
- Recognise OOP in real industry code (Django, SQLAlchemy, scikit-learn, SDKs, games).

---

<a id="ch5-why-oop-concept-explanation"></a>

## Why OOP? Concept Explanation

OOP is a way of organising code around real-world entities rather than around a list of steps. The world is made of things — a car, a dog, a payment, a user — and each thing has properties (data) and behaviours (actions). OOP lets your code mirror that structure.

There are two building blocks to keep straight:

| Term | Meaning | Example |
|------|---------|---------|
| **Class** | A blueprint / template that defines properties + behaviours | `Car` |
| **Object** | A concrete instance built from the blueprint | `my_tesla = Car(...)` |

A class describes:

- **Properties (attributes)** — `brand`, `color`, `speed`
- **Methods (behaviours)** — `accelerate()`, `brake()`

> **A visual analogy — the cookie cutter and the blueprint**
>
> A class is like a cookie cutter (or an architect's blueprint). It is not something you can eat or live in — it just describes the shape. Each object is a cookie (or a house) stamped out from that cutter. One blueprint, many houses, each with its own address and paint colour but the same fundamental design.

!!! note "Beginner takeaway"
    A class is a plan. An object is a real thing made from that plan. You write the plan once and create as many objects as you like.

!!! tip "Intermediate takeaway"
    OOP gives you encapsulation (data and the code that touches it live together), reuse (inheritance), and flexibility (polymorphism). In practice these are what keep a growing codebase maintainable.

!!! abstract "Advanced takeaway"
    OOP is ultimately a tool for managing complexity and coupling for *human* readers. The machine does not care whether you use objects — OOP exists to keep large systems understandable, testable, and extensible. Favour composition where inheritance becomes deep, and prefer clear interfaces (abstraction) at module boundaries.

### Real-world intuition

Think of a bank. Without OOP you have a pile of disconnected functions: `deposit()`, `withdraw()`, `check_balance()`, `apply_interest()` — and the data (account number, balance) floats around in global variables. With OOP, an `Account` object owns its balance and owns the methods that change it. Nothing else can corrupt the balance behind the object's back.

### Procedural vs OOP — the motivation

In procedural style, related functions are just loose, free-floating definitions. Nothing tells you (or the computer) that they belong together:

#### Original Code

In [ ]:
def mobile_banking(): pass
def credit_card(): pass
def dollar_card(): pass

class Payment:
    def mobile_banking(self): pass
    def credit_card(self): pass
    def dollar_card(self): pass
    def esewa(self): pass

(no output — these are just definitions)


#### What This Code Does

The top three lines define three standalone functions. The `Payment` class groups the same conceptual operations (plus `esewa`) as methods that all belong to one logical unit — "ways to pay".

#### Line-by-Line Breakdown

- `def mobile_banking(): pass` — a loose function; `pass` is a placeholder body that does nothing.
- `class Payment:` — declares a class (a namespace that bundles related behaviour).
- `def mobile_banking(self): pass` — a method; the `self` parameter is the object the method is called on.
- `def esewa(self): pass` — extra payment method, naturally grouped inside `Payment`.

#### Why This Output Occurs

Defining a function or class produces no output by itself. Nothing is *called*; the `pass` bodies do nothing.

#### Why the OOP version is better

- **Discoverability** — every payment option lives in one place (`Payment`).
- **Namespacing** — `Payment.credit_card` won't clash with some unrelated `credit_card` elsewhere.
- **State** — methods can share data through `self` (e.g. the logged-in user, the amount).
- **Extensibility** — adding `esewa` is a one-line change in a clearly bounded class.

#### Common Mistakes

- Putting unrelated functions in the same class just to use a class — grouping should be meaningful.
- Forgetting `self` on methods (more on that below).

---

<a id="ch5-classes-objects"></a>

## Classes & Objects

Let's build a real class: a `Dog` with a shared class attribute, per-dog instance attributes, and a method.

### Class attribute vs instance attribute

| Kind | Defined where | Shared? | Example |
|------|---------------|---------|---------|
| **Class attribute** | Directly in the class body | **Shared** by all objects | `species = 'german sepherd'` |
| **Instance attribute** | Inside `__init__` via `self.x = ...` | **Unique** per object | `self.name = name` |

### A teaching moment — the IndentationError

A student first wrote this:

#### Original Code

In [ ]:
class Dog:
    species='german sepherd'   # class attribute
    def __init__(self,name,age):
        self.name=name          # instance attribute
        self.age=age
    def show_name(self):
        print(self.name)

dog1=Dog('tommy',"5")
dog2=Dog('bunny',4)
print(dog1.name); print(dog1.age); print(dog2.name); print(dog2.age)

IndentationError: unindent does not match any outer indentation level


#### What This Code Does

It *intends* to define a `Dog` class and create two dogs. But in the real notebook the indentation was inconsistent — a mix of tabs and spaces, or differing space counts — so Python refused to even parse it.

#### Why This Output Occurs

Python uses indentation to define code blocks; there are no `{ }` braces. Every line in the same block must be indented by the exact same whitespace. If one line uses a tab and the next uses four spaces, they may look identical on screen but they are different bytes to the interpreter. When Python tries to close a block and the new indentation level doesn't line up with any previously opened level, it raises:

```text
IndentationError: unindent does not match any outer indentation level
```

#### How to fix it

1. Use 4 spaces per indentation level — never tabs (PEP 8).
2. Configure your editor to insert spaces when you press Tab, and to show whitespace.
3. In VS Code: "Convert Indentation to Spaces" and set Tab Size = 4.
4. Re-indent the whole block consistently.

#### The corrected version

In [ ]:
class Dog:
    species = 'german sepherd'      # class attribute (shared)

    def __init__(self, name, age):  # constructor
        self.name = name            # instance attribute (unique per dog)
        self.age = age

    def show_name(self):            # instance method
        print(self.name)

dog1 = Dog('tommy', "5")
dog2 = Dog('bunny', 4)
print(dog1.name)
print(dog1.age)
print(dog2.name)
print(dog2.age)

tommy
5
bunny
4


#### Why This Output Occurs

- `Dog('tommy', "5")` calls `__init__`, which stores `name='tommy'` and `age='5'` on that specific object.
- `dog1.name` and `dog2.name` are independent because each object has its own instance attributes.
- Note that `dog1.age` is the string `"5"` (it was passed in quotes) while `dog2.age` is the integer `4`. Python stores exactly what you give it.

#### Line-by-Line Breakdown

- `species = 'german sepherd'` — class attribute; `Dog.species` and `dog1.species` both see it.
- `def __init__(self, name, age):` — the constructor, run automatically on object creation.
- `self.name = name` — binds the argument to *this* object.
- `dog1 = Dog('tommy', "5")` — creates an object; Python passes `dog1` as `self` behind the scenes.

#### Common Mistakes

- Mixing tabs and spaces, which gives you an `IndentationError`. Pick spaces and stay consistent.
- Forgetting `self` in the method signature, which gives you a `TypeError`.
- Expecting `"5"` (string) to behave like `5` (int) — they don't (e.g. `dog1.age + 1` would fail).

---

<a id="ch5-attributes-methods"></a>

## Attributes & Methods

Python has three kinds of methods. The full `Dog` example uses all three:

#### Original Code

In [ ]:
class Dog:
    species='german sepherd'
    def __init__(self,name,age):
        self.name=name
        self.age=age
    def bark(self):                       # instance method
        print(self.name+' is barking')
    @classmethod
    def change_species(cls,new_species):  # class method
        cls.species=new_species
    @staticmethod
    def info():                            # static method
        print("dog are loyal animal")

dog1=Dog('tommy',"3")
print(dog1.name)
print(dog1.age)
dog1.bark()
Dog.change_species("bulldog")
print(Dog.species)
Dog.info()

tommy
3
tommy is barking
bulldog
dog are loyal animal


#### What This Code Does

It defines a `Dog` with an instance method (`bark`), a class method (`change_species`) that mutates the shared `species`, and a static method (`info`) that needs no object state at all.

#### Line-by-Line Breakdown

- `def bark(self):` — instance method; receives the object as `self`, so it can read `self.name`.
- `@classmethod` / `def change_species(cls, new_species):` — class method; receives the *class* as `cls`. `cls.species = new_species` changes the attribute for all dogs.
- `@staticmethod` / `def info():` — static method; receives neither `self` nor `cls`. It's just a regular function living in the class namespace.
- `Dog.change_species("bulldog")` — called on the class; updates the shared species.
- `Dog.info()` — called on the class; prints a constant fact.

#### Why This Output Occurs

- `dog1.name` gives `tommy`, `dog1.age` gives `3` (the string).
- `dog1.bark()` reads `self.name` as `'tommy'`, so it prints `tommy is barking`.
- `Dog.change_species("bulldog")` rebinds the class attribute, so `Dog.species` is now `'bulldog'`.
- `Dog.info()` prints its fixed string — it ignores all object state.

#### The three method types compared

| Method type | First parameter | Decorator | Can access instance data? | Can access/modify class data? | When to use |
|-------------|-----------------|-----------|---------------------------|-------------------------------|-------------|
| **Instance** | `self` | *(none)* | yes | yes, via `self.__class__` | Behaviour that depends on a specific object (`dog1.bark()`) |
| **Class** | `cls` | `@classmethod` | no | yes | Operate on the class itself: alternative constructors, change shared state |
| **Static** | *(none)* | `@staticmethod` | no | no | Utility/helper logically grouped with the class but needing no state |

!!! tip "Rule of thumb"
    Need the object? Use an instance method. Need the class (an alternative constructor, or shared config)? Use `@classmethod`. Need neither? Use `@staticmethod` — or honestly, maybe just a plain function.

#### Common Mistakes

- Calling `Dog.bark()` without an instance, which gives a `TypeError` (no `self`).
- Mutating a mutable class attribute via an instance — it changes it for everyone.
- Using `@staticmethod` then trying to read `self`/`cls` (they don't exist there).

---

<a id="ch5-the-four-pillars-of-oop"></a>

## The Four Pillars of OOP

```mermaid
mindmap
  root((OOP))
    Inheritance
      Code reuse
      Parent → Child
    Polymorphism
      Overloading
      Overriding
    Encapsulation
      public
      _protected
      __private
    Abstraction
      ABC
      @abstractmethod
```

| Pillar | One-liner |
|--------|-----------|
| **Inheritance** | Reuse a parent's code in child classes |
| **Polymorphism** | One interface, many behaviours ("many forms") |
| **Encapsulation** | Bundle data + methods; control access to internals |
| **Abstraction** | Expose *what* an object does, hide *how* |

---

### Pillar 1 — Inheritance

Inheritance lets a child class reuse (and extend or override) the code of a parent class. It is the primary tool for code reuse. Python supports five forms.

> `super()` returns a proxy to the parent class, letting a child call the parent's methods/constructor (e.g. `super().__init__(...)`). This is how you chain initialisation up the hierarchy without hard-coding the parent's name.

#### 1. Single inheritance

One parent, one child.

```mermaid
classDiagram
    Parent <|-- Child
    class Parent {
        +function1()
    }
    class Child {
        +function2()
    }
```

#### Original Code

In [ ]:
class Parent:
    def function1(self):
        print("this is the function from parent class")
class Child(Parent):
    def function2(self):
        print("this is the function from child class")
child1=Child()
child1.function1()
child1.function2()

this is the function from parent class
this is the function from child class


#### What This Code Does

`Child(Parent)` inherits everything from `Parent`. So a `Child` object can call `function1` (inherited) and `function2` (its own).

#### Line-by-Line Breakdown

- `class Child(Parent):` — the `(Parent)` makes `Child` a subclass.
- `child1.function1()` — not defined in `Child`, so Python looks it up in `Parent` and finds it.
- `child1.function2()` — defined directly on `Child`.

#### Why This Output Occurs

Method lookup walks up the inheritance chain: `Child` first, then `Parent`. `function1` is found on `Parent`; `function2` on `Child`.

#### Common Mistakes

- Forgetting the parentheses: `class Child(Parent)` (with) vs `class Child` (without — no inheritance).

#### 2. Multiple inheritance

One child, several parents.

```mermaid
classDiagram
    Father <|-- Child
    Mother <|-- Child
    class Father { +function1() }
    class Mother { +function2() }
    class Child  { +function3() }
```

#### Original Code

In [ ]:
class Father:
    def function1(self): print("He is my Father")
class Mother:
    def function2(self): print("She is my Mother")
class Child(Father,Mother):
    def function3(self): print("i am their child")
child1=Child()
child1.function1(); child1.function2(); child1.function3()

He is my Father
She is my Mother
i am their child


#### What This Code Does

`Child(Father, Mother)` inherits from both parents, so it has access to `function1`, `function2`, and its own `function3`.

#### Why This Output Occurs

`Child` searches itself, then `Father`, then `Mother` (left-to-right, per the MRO — see the hybrid section). Each method is found in the appropriate parent.

#### Common Mistakes

- Two parents defining the same method name — the one earliest in the MRO wins; the other is silently shadowed.

#### 3. Multilevel inheritance

A chain: Grandfather → Father → Child. Here `super()` chains the constructors.

```mermaid
classDiagram
    Grandfather <|-- Father
    Father <|-- Child
    class Grandfather { +grandfather_name }
    class Father { +father_name }
    class Child { +son_name }
```

#### Original Code

In [ ]:
class Grandfather:
    def __init__(self,grandfather_name):
        self.grandfather_name=grandfather_name
class Father(Grandfather):
    def __init__(self,father_name,grandfather_name):
        super().__init__(grandfather_name)
        self.father_name=father_name
class Child(Father):
    def __init__(self,son_name,father_name,grandfather_name):
        super().__init__(father_name,grandfather_name)
        self.son_name=son_name
child1=Child('tommy','john','michael')
print(child1.son_name); print(child1.father_name); print(child1.grandfather_name)

tommy
john
michael


#### What This Code Does

Each constructor stores its own attribute and calls `super().__init__(...)` to let the parent store *its* attribute. The single `Child` object ends up with all three names.

#### Line-by-Line Breakdown

- `Child.__init__` stores `son_name`, then calls `super().__init__(father_name, grandfather_name)`, which runs `Father.__init__`.
- `Father.__init__` stores `father_name`, then calls `super().__init__(grandfather_name)`, which runs `Grandfather.__init__`.
- `Grandfather.__init__` stores `grandfather_name`.

#### Why This Output Occurs

`super().__init__()` walks the chain upward, so each level adds its attribute to the same object. The final object carries all three.

#### Common Mistakes

- Forgetting `super().__init__(...)`, so the parent's attributes never get set, and you hit an `AttributeError` later.
- Passing arguments in the wrong order to `super().__init__`.

#### 4. Hierarchical inheritance

One parent, many children.

```mermaid
classDiagram
    Father <|-- child1
    Father <|-- child2
    Father <|-- child3
    class Father { +father_name }
    class child1 { +child_name }
    class child2 { +child_name }
    class child3 { +child_name }
```

#### Original Code

In [ ]:
class Father:
    def __init__(self,father_name):
        self.father_name=father_name
class child1(Father):
    def __init__(self,child_name,father_name):
        super().__init__(father_name)
        self.child_name=child_name
class child2(Father):
    def __init__(self,child_name,father_name):
        super().__init__(father_name)
        self.child_name=child_name
# (and a child3 similarly)
c1=child1('tommy','john')
c2=child2('jerry','john')
print(c1.child_name); print(c1.father_name); print(c2.child_name); print(c2.father_name)

tommy
john
jerry
john


#### What This Code Does

`child1`, `child2` (and `child3`) all inherit from the same `Father`. Each child shares the father's name but has its own `child_name`.

#### Why This Output Occurs

Both children call `super().__init__('john')`, so each independently stores `father_name='john'` plus its own `child_name`.

#### Common Mistakes — the class-name-shadowing bug

In the original notebook the instances were named the same as the classes:

In [ ]:
child1 = child1('tommy', 'john')   # shadows the class!

After this line, the name `child1` no longer refers to the class — it now refers to an object. So if you try to make another instance:

In [ ]:
child1 = child1('bunny', 'john')   # TypeError: 'child1' object is not callable

Python now thinks `child1` is the object you just made, and objects aren't callable like a constructor. The fix is to use distinct, lowercase variable names (`c1`, `c2`) that differ from the class names — and by convention class names should be `PascalCase` anyway (`Child1`, `Child2`). Reusing a class name as a variable quietly destroys your ability to create further instances, and it's a classic bug that's hard to spot.

#### 5. Hybrid inheritance

A combination of the above forms — here, a multilevel `Village → School` plus hierarchical `Student`/`Teacher` under `School`.

```mermaid
classDiagram
    Village <|-- School
    School <|-- Student
    School <|-- Teacher
    class Village { +func1() }
    class School  { +func2() }
    class Student { +func3() }
    class Teacher { +func4() }
```

#### Original Code

In [ ]:
class Village:
    def func1(self):
        print("this fucntion is in  village ")
class School(Village):
    def func2(self):
        print("this function is in school")
class Student(School):
    def func3(self): 
        print("this function is in school")
class Teacher(School):
    def func4(self): 
        print("this function is in school")
teacher1=Teacher()
teacher1.func1()
teacher1.func2()
teacher1.func4()

this fucntion is in  village 
this function is in school
this function is in school


#### What This Code Does

`Teacher` inherits from `School`, which inherits from `Village`. So a `Teacher` object reaches `func1` (Village), `func2` (School), and its own `func4`.

#### Why This Output Occurs

Lookup climbs `Teacher → School → Village`. `func4` is on `Teacher`, `func2` on `School`, `func1` on `Village`. (Note the original typos `fucntion` and `village ` with the trailing space are preserved in the printed output.)

!!! warning "MRO and the diamond problem"
    When inheritance graphs branch and re-merge (the classic diamond: `D` inherits `B` and `C`, both inheriting `A`), Python must decide the order in which to search parents. It uses the Method Resolution Order (MRO), computed with the C3 linearization algorithm. Inspect it with `ClassName.__mro__` or `ClassName.mro()`. The MRO guarantees each ancestor is visited once, in a consistent left-to-right, depth-respecting order — which is why cooperative `super()` calls work correctly even in diamonds.

#### Common Mistakes

- Building deep or wide hybrid hierarchies "because you can" — they get hard to reason about. Prefer composition when inheritance gets tangled.

---

### Pillar 2 — Polymorphism

Polymorphism means "many forms": the same operation behaves differently depending on the object. There are two flavours:

- **Compile-time** (method overloading) — same method name, different signatures.
- **Run-time** (method overriding) — a child redefines a parent's method.

#### Built-in polymorphism you already use

In [ ]:
len("abcd")      # 4   -> length of a string
len([1, 2, 3])   # 3   -> length of a list
'abv' + 'def'    # 'abvdef'  -> + concatenates strings
5 + 6            # 11        -> + adds numbers

The same `len()` and the same `+` operator do different things based on the operand type. The `+` operator doing both concatenation and addition is called operator overloading — Python dispatches to `__add__` on the object.

#### Method overloading — Python does NOT support it

#### Original Code

In [ ]:
class calculator:
    def add(self,num1,num2):
        return num1+num2
    def add(self,num1,num2,num3):
        return num1+num2+num3
add1=calculator()
add1.add(1,2)

TypeError: calculator.add() missing 1 required positional argument: 'num3'


#### What This Code Does

It tries to define two `add` methods — one with two numbers, one with three — expecting Python to pick the right one. It can't.

#### Why This Output Occurs

In Python a class body is just a namespace, and the second `def add` simply overwrites the first. Only the three-argument version survives. So `add1.add(1, 2)` is missing `num3`, which raises a `TypeError`. Python has no true method overloading — there is only ever one method per name.

#### Common Mistakes

- Expecting C++/Java-style overloading. In Python, the last definition wins.

#### Faking overloading with default arguments

#### Original Code

In [ ]:
class calculator:
    def add(self,num1,num2=None,num3=None):
        if num2 is not None and num3 is not None:
            return num1+num2+num3
        elif num2 is not None:
            return num1+num2
        else:
            return num1
calc=calculator()
print(calc.add(5)); print(calc.add(5,10)); print(calc.add(5,10,15))

5
15
30


#### What This Code Does

One method with optional parameters (`=None`) inspects which arguments were supplied and branches accordingly.

#### Why This Output Occurs

- `add(5)` — `num2`/`num3` are `None`, so it returns `5`.
- `add(5, 10)` — only `num2` given, so it returns `15`.
- `add(5, 10, 15)` — all given, so it returns `30`.

#### Faking overloading with `*args`

#### Original Code

In [ ]:
class calculator:
    def add(self,*args):
        return sum(args)
calc=calculator()
print(calc.add(5)); print(calc.add(5,10)); print(calc.add(5,10,15))

5
15
30


#### What This Code Does

`*args` collects any number of positional arguments into a tuple; `sum()` adds them all. This is the cleanest, most general approach.

#### Why This Output Occurs

`args` becomes `(5,)`, `(5, 10)`, `(5, 10, 15)` respectively; `sum` reduces each to `5`, `15`, `30`.

#### Common Mistakes

- Using `*args` when arguments have distinct meanings (e.g. `width`, `height`) — named parameters are clearer there.

#### Method overriding (run-time polymorphism)

```mermaid
classDiagram
    Animal <|-- Dog
    Animal <|-- Cat
    class Animal { +sound() }
    class Dog { +sound(sound) }
    class Cat { +sound() }
```

#### Original Code

In [ ]:
class Animal:
    def sound(self):
        print("animal make sound")
class Dog(Animal):
    def sound(self,sound):
        print(" dog is barking",sound)
        super().sound()
class Cat(Animal):
    def sound(self):
        print("meow")
animal=Animal(); dog=Dog(); cat=Cat()
animal.sound(); dog.sound("woof"); cat.sound()

animal make sound
 dog is barking woof
animal make sound
meow


#### What This Code Does

`Dog` and `Cat` each override the parent's `sound`. `Dog` additionally calls `super().sound()` to also run the parent version.

#### Line-by-Line Breakdown

- `Animal.sound(self)` — base behaviour.
- `Dog.sound(self, sound)` — overrides it, takes an extra argument, then calls `super().sound()` (the `Animal` version).
- `Cat.sound(self)` — simply overrides with `meow`.

#### Why This Output Occurs

- `animal.sound()` runs the base version, printing `animal make sound`.
- `dog.sound("woof")` prints ` dog is barking woof` (note the leading space in the string literal), then `super().sound()` runs `Animal.sound`, printing `animal make sound`.
- `cat.sound()` runs the overridden version, printing `meow`.

This is run-time polymorphism: the same call `obj.sound()` does different things depending on the actual object type.

#### Common Mistakes

- Changing the method signature when overriding (`Dog.sound` requires an argument the base doesn't) breaks substitutability — `dog.sound()` with no args would now fail. Keep overrides signature-compatible where you can.

---

### Pillar 3 — Encapsulation

Encapsulation bundles data with the methods that operate on it, and controls access to the internals. Python signals intent with naming conventions; it does not hard-enforce most of it.

| Modifier | Syntax | Convention / meaning | Enforcement |
|----------|--------|----------------------|-------------|
| **Public** | `name` | Free to use anywhere | None — fully accessible |
| **Protected** | `_name` | "Internal — use with care; subclasses OK" | **Convention only**, still accessible |
| **Private** | `__name` | "Do not touch from outside" | **Name-mangled** to `_Class__name` (discouraged, not blocked) |

#### Public attributes

#### Original Code

In [ ]:
class Employee:
    def __init__(self,name): self.name=name
    def display_name(self): print(self.name)
emp=Employee("ram"); emp.display_name(); print(emp.name)

ram
ram


#### Why This Output Occurs

`name` is public, so both the method `display_name()` and the direct access `emp.name` print `ram`.

#### Protected attributes (single underscore)

#### Original Code

In [ ]:
class Employee:
    def __init__(self,name,age):
        self.name=name
        self._age=age   # protected
class SubEmployee(Employee):
    def show_age(self): print("Age",self._age)
emp=SubEmployee('Ross',30)
print(emp.name); emp.show_age()

Ross
Age 30


#### Why This Output Occurs

`_age` is protected by convention only. The subclass `SubEmployee` reads `self._age` freely — and so could outside code. The underscore is a signal to other developers ("internal, handle with care"), not a lock.

#### Private attributes (double underscore, name mangling)

#### Original Code

In [ ]:
class Employee:
    def __init__(self,name,salary):
        self.name=name
        self.__salary=salary   # private
    def show_salary(self): print("salary",self.__salary)
emp=Employee("Robert downey jr",10000000)
print(emp.name); emp.show_salary()
print(emp.__salary)   # this line fails

Robert downey jr
salary 10000000
AttributeError: 'Employee' object has no attribute '__salary'


#### Why This Output Occurs

A double-underscore prefix triggers name mangling: inside the class, `self.__salary` is rewritten by Python to `self._Employee__salary`. So:

- `show_salary()` works — it references `__salary` *inside* the class, which mangles correctly.
- `emp.__salary` from *outside* looks for a literal attribute named `__salary`, which doesn't exist, so you get an `AttributeError`.

!!! warning "Python has no *true* private"
    Name mangling is not real access control. The value is still reachable:

In [ ]:
print(emp._Employee__salary)   # 10000000


NameError: name 'emp' is not defined

    Double underscore mainly prevents *accidental* clashes in subclasses. Treat it as "strongly discouraged to access", not "impossible".

#### Common Mistakes

- Believing `__x` is secure — it is not. Use it for intent, not security.
- Accidentally creating two attributes by mixing `__x` and `_Class__x`.

#### Getter / setter with validation

#### Original Code

In [ ]:
class Employee:
    def __init__(self):
        self.__salary=50000
    def get_salary(self):
        return self.__salary
    def set_salary(self,amount):
        if amount>0:
            self.__salary=amount
        else:
            print("Invalid amount")
emp=Employee()
print(emp.get_salary())
emp.set_salary(10000000)
print(emp.get_salary())

50000
10000000


#### What This Code Does

Keeps `__salary` private and exposes controlled access: `get_salary()` reads it, `set_salary()` validates before writing (it rejects non-positive values).

#### Why This Output Occurs

Initial salary is `50000`. `set_salary(10000000)` passes the `amount > 0` check, so the value updates; the second `get_salary()` returns the new value.

!!! tip "This is the manual version of `@property`"
    Writing explicit `get_`/`set_` methods works, but Python's idiomatic approach is the `@property` decorator, which lets `emp.salary = 10000000` look like plain attribute access while still running your validation. That is covered in **Chapter 4** → [`chapter_04_decorators_properties/index.md`](chapter_04_decorators_properties/index.md).

#### Common Mistakes

- Forgetting validation in the setter (the whole point of encapsulation).
- Exposing the private attribute name directly, defeating the getter/setter.

---

### Pillar 4 — Abstraction

Abstraction hides the implementation and exposes only the interface — *what* an object can do, not *how*.

> **Real-world intuition:** when you call `pd.read_csv("data.csv")` you have no idea how pandas parses the file, handles encodings, or builds the DataFrame — and you don't need to. The complex internals are abstracted behind a simple interface. That's abstraction in action.

In Python, abstract base classes (`abc.ABC`) let you define a contract: methods that subclasses must implement.

#### Original Code

In [ ]:
from abc import ABC, abstractmethod
class Greet(ABC):
    @abstractmethod
    def say_hello(self): pass
class English(Greet):
    def say_hello(self): print("hello in english")
class Nepali(Greet):
    def say_hello(self): print("namaste in nepali")
e=English(); n=Nepali()
e.say_hello(); n.say_hello()

hello in english
namaste in nepali


#### What This Code Does

`Greet` is an abstract base class declaring that every greeter must provide `say_hello()`. `English` and `Nepali` supply concrete implementations.

#### Line-by-Line Breakdown

- `from abc import ABC, abstractmethod` — imports the tools for abstraction.
- `class Greet(ABC):` — inheriting `ABC` marks the class abstract.
- `@abstractmethod` / `def say_hello(self): pass` — declares a required method with no body.
- `class English(Greet):` — must override `say_hello`, or it stays abstract.
- `e = English()` — allowed, because `English` implements the contract.

#### Why This Output Occurs

Each subclass provides its own `say_hello`, so the calls dispatch to the concrete implementation. (This is also polymorphism — same interface, different behaviour.)

!!! warning "You cannot instantiate an abstract class"
    Calling `Greet()` directly raises:
```text
    TypeError: Can't instantiate abstract class Greet with abstract method say_hello
```
    The whole point is to force subclasses to fill in the blanks. If a subclass forgets to implement *any* abstract method, *it* also becomes un-instantiable.

#### Common Mistakes

- Forgetting to inherit `ABC` (or use `metaclass=ABCMeta`) — then `@abstractmethod` is not enforced.
- Leaving a subclass without all abstract methods implemented, which means you can't instantiate it.

---

<a id="ch5-real-industry-usage"></a>

## Real Industry Usage

You'll find OOP throughout production Python:

- **Django / SQLAlchemy models** — a database table is a class; each row is an object. `class User(models.Model)` uses inheritance from the framework's base, and fields are declared as class attributes.
- **scikit-learn estimator API** — every model (`LinearRegression`, `RandomForestClassifier`, `KMeans`) implements the same `.fit()` / `.predict()` / `.transform()` interface. That uniformity is polymorphism: you can swap estimators in a pipeline without changing the calling code.
- **Abstract base classes for plugins/interfaces** — frameworks define ABCs (a `BaseStorage`, a `BaseCommand`) so third-party plugins implement a guaranteed contract. This is abstraction used as an extension point.
- **Encapsulation in SDKs/libraries** — a client object (an API SDK, say) hides connection pools, retries, and auth tokens behind public methods like `client.send(...)`. Internals are `_private` so the public surface stays stable across versions.
- **Game & GUI objects** — `Player`, `Enemy`, `Button`, `Window` are classes with state (position, health) and behaviour (`move()`, `render()`, `on_click()`). Inheritance models entity hierarchies; overriding customises behaviour per type.

---

<a id="ch5-quick-recap"></a>

## Quick Recap

- A **class** is a blueprint; an **object** is an instance. `__init__` is the constructor; `self` is the current object.
- **Class attributes** are shared; **instance attributes** are per-object.
- Three method types: **instance** (`self`), **class** (`@classmethod`, `cls`), **static** (`@staticmethod`, neither).
- **Inheritance** (5 types) reuses code; `super()` chains to the parent; the **MRO** resolves multiple inheritance.
- **Polymorphism**: Python has no true overloading (last `def` wins) — fake it with defaults or `*args`; overriding gives run-time polymorphism.
- **Encapsulation**: `public`, `_protected` (convention), `__private` (name-mangled, not truly private).
- **Abstraction**: `ABC` + `@abstractmethod` define contracts; abstract classes can't be instantiated.
- Indentation must be consistent (4 spaces) or you get an `IndentationError`.
- Never reuse a class name as a variable — it shadows the class.

---

<a id="ch5-interview-questions"></a>

## Interview Questions

### Beginner

??? note "What is the difference between a class attribute and an instance attribute?"
    A class attribute is defined in the class body and shared by all instances (e.g. `species`). An instance attribute is set per-object inside `__init__` via `self.x = ...` and is unique to that object. Reassigning a class attribute through the class changes it for everyone; assigning through an instance creates a shadowing instance attribute.

??? note "What is `self`, and why is it the first parameter of methods?"
    `self` is a reference to the current object. Python passes it automatically when you call `obj.method()`. It lets the method read and write that specific object's data (`self.name`). It's a convention — the name could technically be anything — but always use `self`.

??? note "What is `__init__`?"
    It's the constructor: a special method run automatically when you create an object. It initialises the object's instance attributes. It returns `None` — its job is to set up `self`, not to return a value.

### Intermediate

??? note "What's the difference between `@staticmethod` and `@classmethod`?"
    A class method takes `cls` (the class) as its first argument and can read or modify class-level state, or act as an alternative constructor. A static method takes neither `self` nor `cls` — it's just a function grouped inside the class for organisation, with no access to instance or class state.

??? note "Does Python support method overloading?"
    No. Defining two methods with the same name just makes the last one overwrite the earlier. You emulate overloading with default arguments or `*args`/`**kwargs`, branching on what was actually passed. (Operator overloading via dunder methods like `__add__` *is* supported, which is a different thing.)

??? note "Explain `super()` and when you'd use it."
    `super()` returns a proxy to the parent class in the MRO, letting a child call the parent's methods — most commonly `super().__init__(...)` to run the parent's constructor while adding the child's own setup. It enables cooperative inheritance without hard-coding parent names.

### Advanced

??? note "What is the MRO and how does Python compute it?"
    The Method Resolution Order is the linear order in which Python searches base classes for an attribute or method. It's computed with the C3 linearization algorithm, which guarantees a consistent order that respects local precedence and monotonicity, visiting each ancestor exactly once. Inspect it with `Class.__mro__`. It's what makes the diamond problem resolvable and `super()` calls cooperate correctly.

??? note "Is anything *truly* private in Python?"
    No. `_protected` is convention only. `__private` triggers name mangling (`__x` becomes `_Class__x`) to avoid subclass clashes, but the value is still reachable as `obj._Class__x`. Python follows "we're all consenting adults" — privacy is signalled, not enforced.

??? note "Abstract class vs interface — what's the difference in Python?"
    Python has no separate `interface` keyword. An abstract base class (`abc.ABC`) can define both abstract methods (a contract) and concrete methods/state. A pure "interface" is just an ABC where every method is abstract. ABCs can't be instantiated and force subclasses to implement all abstract methods.

---

<a id="ch5-practice-exercises"></a>

## Practice Exercises

### **Easy**

1. Create a `Book` class with instance attributes `title` and `author`, and a method `describe()` that prints `"<title> by <author>"`. Instantiate two books and call `describe()` on each.
2. Add a class attribute `count` to `Book` that increments in `__init__` every time a book is created. Print the total after making three books.

### **Medium**

1. Build a `Shape` base class and `Circle`/`Rectangle` subclasses. Give each an `area()` method (override it). Store shapes in a list and print every area in a loop (polymorphism).
2. Create a `BankAccount` with a private `__balance`. Provide `deposit(amount)` and `withdraw(amount)` methods that validate (no negative deposits, no overdraft). Expose `get_balance()`.
3. Write a `@classmethod` alternative constructor `Book.from_string("title|author")` that splits the string and returns a `Book`.

### **Hard**

1. Implement multilevel inheritance `Vehicle → Car → SportsCar`, each constructor using `super().__init__(...)`. The final object should carry attributes from all three levels.
2. Define an abstract `PaymentMethod(ABC)` with `@abstractmethod def pay(self, amount)`. Implement `CreditCard`, `Esewa`, and `MobileBanking`. Process a list of payments polymorphically. Verify that instantiating `PaymentMethod()` directly raises `TypeError`.

---

<a id="ch5-challenge-project-mini-library-management-system"></a>

## Challenge Project — Mini Library Management System

Model a small library that exercises all four pillars.

**Spec**

- An abstract `LibraryItem(ABC)` with abstract method `describe()` and a `_checked_out` protected flag.
- Concrete subclasses `Book`, `DVD`, `Magazine` (inheritance), each overriding `describe()` (polymorphism).
- A `Member` class with a private `__borrowed_items` list and methods `borrow(item)` / `return_item(item)` with validation (encapsulation).
- A `Library` class holding items and members; method `checkout(member, item)` that flips `_checked_out` and updates the member.

**Hints**

- Use `from abc import ABC, abstractmethod` for `LibraryItem`.
- Override `describe()` differently per item type and loop over a mixed list to print all — that's polymorphism.
- Keep `__borrowed_items` private; expose a read-only view via a getter.
- Add a `@classmethod` `Library.from_catalog(list_of_dicts)` as an alternative constructor.
- Bonus: raise a clear error when a member borrows an already-checked-out item.

---

Previous: [Chapter 4 — Decorators & Properties](chapter_04_decorators_properties/index.md)

**You've completed the handbook.** You went from comprehensions all the way to object-oriented programming — the building blocks of clean, professional Python. Go build something real, and revisit any chapter anytime from the [Home page](index.md).

---